### ISSUE TITLE
Custom Config Page: View Letter Types

### ISSUE THREAD

**Issue by jordanngtw** [PublicDataWorks/complaint-manager#140]
### Business Context:
This is the first story in the "allowing users to edit their own letter template" epic. 

Here are the full designs
https://app.mural.co/invitation/mural/twma7655/1660587549250?sender=u75625ab6804bb6b0608c6642&key=eb598bbb-8fd9-4d3a-a661-4dd5a23d884c

Scope of the Epic:
1. [this story] View letter types - expand to see template, but no editing
2. Edit button - this brings up the edit letter modal, which will allow you to do all of the editing
3. Add new letter type - this is a button at the bottom, it brings up a modal just like the edit modal but with nothing pre-populated
4. Delete - a delete button next to edit, like we do elsewhere. this brings up the standard confirmation modal, and users either delete or cancel from there. 
5. Add generated HTML preview - add a button to allow users to see what their edits are doing in real-ish time!

**As a** 
**I want**
**So that** 

### In Scope
1. View letter type details on custom configuration page
6. Expand to show letter templates

### Out of Scope
1. Editing
2. HTML generated from example data to show letter output
7. 

### Open Questions
1.
2.
3.

## Acceptance Criteria

1. Scenario: 
Given I am logged in
When i navigate to the admin portal
Then I am able to see letter types

2. Scenario: Expaaaaaaand
Given i am on the admin portal page
When i click on a letter type
Then the row expands and i am able to see the template

### Checklist (should be reviewed before grooming as the BA or Pair are writing the card—NOT reviewed for the first time at grooming)
0. Discuss the technical implementation of this card.
1. Discuss how this feature would be included in or affect the Audit Log.
2. In respect to security, what could go wrong? Brainstorm threats using STRIDE model, especially if this card introduces a new technical architecture or design pattern. (TIMEBOX: 7 mins) https://docs.google.com/document/d/18AFl1d3SRieI4d_8R3GyEazqQOycLNDHGN_vOYIHuiE/edit#heading=h.aio9zb5j63wl
3. Ensure any open questions have been resolved with stakeholders.
8. Determine if documentation should be referenced or created.
9. Ensure to include all necessary mockups to this card.
10. Discuss what success/failure user feedback messages would be present, if any occur (front end/back end).
11. Discuss why this feature would not be implemented behind a toggle / what would happen if this card was partially done while a release branch was being cut.
12. If this card is part of a sequence of cards, discuss if this card should be blocked until the testing of previous  cards in the sequence have been finished.
13. Have we added edge cases as ACs that we're considered from a QA perspective
14. Does this card overlap with any entities outlined in [API Housekeeping](https://www.pivotaltracker.com/story/show/173963545)?  

**Notes:**

**Comment by andrew-rist-tw** [comment]
[Design](https://app.mural.co/invitation/mural/twma7655/1660587549250?sender=uc140ee4900b34ac03eee8350&key=eb598bbb-8fd9-4d3a-a661-4dd5a23d884c)

**Comment by jordanngtw** [comment]
Wireframe:

<img width="1269" alt="Screen Shot 2022-08-16 at 10 40 43 AM" src="https://user-images.githubusercontent.com/86383902/184921430-523b6a4a-8ba7-425c-a88c-b0d371acaed2.png">

**Comment by jordanngtw** [comment]
<img width="1369" alt="Screen Shot 2022-08-16 at 11 01 17 AM" src="https://user-images.githubusercontent.com/86383902/184925780-7aadb394-725a-461e-9f68-643fae5a00aa.png">
