### ISSUE TITLE
Move Non-Visualization Text for Public Sections of the CM to the Database

### ISSUE THREAD

**Issue by andrew-rist-tw** [PublicDataWorks/complaint-manager#161]
### Business Context:
[The public data dashboard](https://noipm-ci.herokuapp.com/data) has a lot of text on it where the organization gives context for the data that they are presenting.  We have a strong hypothesis that orgs will want, at a minimum, to customize that text rather than using New Orleans' text.

**As an** organization adopting complaint-manager
**I want** to be able to customize the Public Data Dashboard
**So that** I can have control of the data I display and the context I provide for it

### In Scope
1. Determine a database table design that will encompass all the text on tag glossary and about pages, along with the text at the top of the public data dashboard that is not directly related to a certain visualization
2. Migrate and seed said table with NOLA data
3. Create a [public handler](https://sites.google.com/thoughtworks.com/tw-invisible-institute-wiki/development-resources/how-to-create-a-public-service-handler) to get said data
4. Use data retrieved from the handler to populate the public pages

### Out of Scope
1. Allowing orgs to customize
5.
6.

### Open Questions
1.
2.
3.

## Acceptance Criteria

1. Scenario: 
Given I am a public page of complaint manager
When somebody loads me
Then my text is loaded from the database so that different orgs can set that text to what they like

2. Scenario: 
Given
When
Then

### Checklist (should be reviewed before grooming as the BA or Pair are writing the card—NOT reviewed for the first time at grooming)
0. Discuss the technical implementation of this card.
1. Discuss how this feature would be included in or affect the Audit Log.
2. In respect to security, what could go wrong? Brainstorm threats using STRIDE model, especially if this card introduces a new technical architecture or design pattern. (TIMEBOX: 7 mins) https://docs.google.com/document/d/18AFl1d3SRieI4d_8R3GyEazqQOycLNDHGN_vOYIHuiE/edit#heading=h.aio9zb5j63wl
3. Ensure any open questions have been resolved with stakeholders.
7. Determine if documentation should be referenced or created.
8. Ensure to include all necessary mockups to this card.
9. Discuss what success/failure user feedback messages would be present, if any occur (front end/back end).
10. Discuss why this feature would not be implemented behind a toggle / what would happen if this card was partially done while a release branch was being cut.
11. If this card is part of a sequence of cards, discuss if this card should be blocked until the testing of previous  cards in the sequence have been finished.
12. Have we added edge cases as ACs that we're considered from a QA perspective
13. Does this card overlap with any entities outlined in [API Housekeeping](https://www.pivotaltracker.com/story/show/173963545)?  

**Notes:**

**Comment by andrew-rist-tw** [comment]
[Here's a wiki for creating a public handler](https://sites.google.com/thoughtworks.com/tw-invisible-institute-wiki/development-resources/how-to-create-a-public-service-handler) (this handler will need to be public)

**Comment by mariaDelSignore** [comment]
![Screen Shot 2022-11-03 at 10 46 35 AM](https://user-images.githubusercontent.com/102056899/199782893-4b0ef708-81a9-468c-abb9-8641dbfaa50d.png)

**Comment by mariaDelSignore** [comment]
moving this story into backlog to revisit after we have a better understanding of what Hawaii will need for the public dashboard. 

created a branch: public-pages which has a migration for a new table from the above image.
