### ISSUE TITLE
Read Only Role Can't See Attachments for Anonymous Users

### ISSUE THREAD

**Issue by jordanngtw** [PublicDataWorks/complaint-manager#166]
### Business Context:

The letter to complainant contains the complainant's name - read only people shouldn't be able to get anonymous complainants' names. We want to restrict access to ALL attachments because there could be pictures of the complainant, or other documents with the complainant's name in them. 

**As an** anonymous complainant
**I want** to prevent read-only users from seeing attachments
**So that** my name and information are not exposed to them

### In Scope
1. read only users cannot see any attachments for a case that has at least one anonymous complainant or anonymous witness

### Out of Scope
1.

### Open Questions
1.

## Acceptance Criteria

1. Scenario: Read Only User goes to case with anonymous user
Given user is logged in as read only
When they go to a case that has been marked as anonymous
Then they do not see any attachments.

2. Scenario: Read only role unable to access attachments through browser
Given user is logged in as read only
When they attempt to reach an attachment some other way (??? idk i'm not a hacker)
Then they are unable to access it

### Checklist (should be reviewed before grooming as the BA or Pair are writing the card—NOT reviewed for the first time at grooming)
0. Discuss the technical implementation of this card.
1. Discuss how this feature would be included in or affect the Audit Log.
2. In respect to security, what could go wrong? Brainstorm threats using STRIDE model, especially if this card introduces a new technical architecture or design pattern. (TIMEBOX: 7 mins) https://docs.google.com/document/d/18AFl1d3SRieI4d_8R3GyEazqQOycLNDHGN_vOYIHuiE/edit#heading=h.aio9zb5j63wl
3. Ensure any open questions have been resolved with stakeholders.
4. Determine if documentation should be referenced or created.
5. Ensure to include all necessary mockups to this card.
6. Discuss what success/failure user feedback messages would be present, if any occur (front end/back end).
7. Discuss why this feature would not be implemented behind a toggle / what would happen if this card was partially done while a release branch was being cut.
8. If this card is part of a sequence of cards, discuss if this card should be blocked until the testing of previous  cards in the sequence have been finished.
9. Have we added edge cases as ACs that we're considered from a QA perspective
10. Does this card overlap with any entities outlined in [API Housekeeping](https://www.pivotaltracker.com/story/show/173963545)?  

**Notes:**

**Comment by andrew-rist-tw** [comment]
use `anonymous:view` permission to control whether the attachments section shows at all
