### ISSUE TITLE
Letter View Allegation Details Font

### ISSUE THREAD

**Issue by jordanngtw** [PublicDataWorks/complaint-manager#207]
**Describe the bug**
the text for allegation details at the bottom of the letter review screen is smaller than the rest of the text (and ugly)

**To Reproduce**
1. Go to[ this link ](https://noipm-ci.herokuapp.com/cases/4025/letter/review) (Case review page)
2. The "allegation details" font is WRONG SIZE
**Expected behavior**
Make it the same size as the rest of the text above it

**Screenshots**

<img width="640" alt="Screen Shot 2022-10-21 at 11 55 57 AM" src="https://user-images.githubusercontent.com/86383902/197249033-a4c71348-6b4d-46d1-9982-ba1dc2dd5503.png">

**Comment by mariaDelSignore** [comment]
on case review page
