### ISSUE TITLE
Create Person in Custody PERSON_TYPE and Search Roster when selected

### ISSUE THREAD

**Issue by andrew-rist-tw** [PublicDataWorks/complaint-manager#228]
### Business Context:
We need to let the radio buttons for the Complainant Type (currently Civilian, Police Officer, Civilian (NOPD)) be determined on an org by org basis.  Since PERSON_TYPE hasn't been moved out of instance-files, we will go ahead and use it from instance-files, but we need to add a dimension to PERSON_TYPE that tells us whether there should be an input form (as civilian currently has) or whether the creation flow takes you to a new page to search for someone from a roster (as the other two types currently have).  For this story we will just do the person in custody type and have that route to a new inmates search page that is modeled after the officer search page.

**As a** new org adopting CM
**I want** to be able to define what radio buttons appear for complainant type when creating a case and what happens when they're selected
**So that** I can attach complainant types to a case that make sense for my use-case

### In Scope
1. Tweak PERSON_TYPE in instance-files to reflect the action to take for the person in custody type
2. Populate Radio buttons on the CreateCaseDialog and determine submit action based on PERSON_TYPE
3. When "Person in Custody" is selected, show the search page (Creating and routing to separate search pages for separate PERSON_TYPEs)

### Out of Scope
1. Adding a missing person in custody
2. unknown person in custody
3. other person types
4. Adding from the Case Details Page

### Open Questions
1.
2.
5.

## Acceptance Criteria

1. Scenario: Adding PiC [THIS IS DEFAULT VIEW]
Given I have selected the Create New Case button and the dialog has popped up 
When the PiC radio button is selected
Then the "create and search" button shows up

2. Scenario: Search Roster
Given I have selected PiC and clicked Create and Search
When I search for a person in custody
AND click Select
AND click Add to Case
Then that case is created and the PiC is added as the complainant

### Checklist (should be reviewed before grooming as the BA or Pair are writing the card—NOT reviewed for the first time at grooming)
0. Discuss the technical implementation of this card.
1. Discuss how this feature would be included in or affect the Audit Log.
2. In respect to security, what could go wrong? Brainstorm threats using STRIDE model, especially if this card introduces a new technical architecture or design pattern. (TIMEBOX: 7 mins) https://docs.google.com/document/d/18AFl1d3SRieI4d_8R3GyEazqQOycLNDHGN_vOYIHuiE/edit#heading=h.aio9zb5j63wl
3. Ensure any open questions have been resolved with stakeholders.
6. Determine if documentation should be referenced or created.
9. Ensure to include all necessary mockups to this card.
10. Discuss what success/failure user feedback messages would be present, if any occur (front end/back end).
11. Discuss why this feature would not be implemented behind a toggle / what would happen if this card was partially done while a release branch was being cut.
12. If this card is part of a sequence of cards, discuss if this card should be blocked until the testing of previous  cards in the sequence have been finished.
13. Have we added edge cases as ACs that we're considered from a QA perspective
14. Does this card overlap with any entities outlined in [API Housekeeping](https://www.pivotaltracker.com/story/show/173963545)?  

**Notes:**

**Comment by andrew-rist-tw** [comment]
COMPLAINTANT INFORMATION

Remove:              Civilian

Police Officer

Civilian (NOPD)

 

Add:                      Department Staff - dropdown list (?) for:

Adult Correction Officer (ACO)

Medical Practitioner

Mental Health Professional

Program Staff

                                Person in Custody – Dropdown list (?) for Location:

o             Halawa Correctional Facility

o             Waiawa Correctional Facility

o             Kulani Correctional Facility

o             Saguaro Correctional Facility (private facility in AZ)

o             Oahu Community Correctional Center

o             Women’s Community Correctional Center

o             Hawaii Community Correctional Center

o             Kauai Community Correctional Center

o             Maui Community Correctional Center

Family/Friend

Community Member/Organization

Legislator

Commissioner

Other

**Comment by jordanngtw** [comment]
![PIC Search and Create](https://user-images.githubusercontent.com/86383902/214368463-86f0413c-b253-4391-9125-42d5719d0404.png)
![Select Department Staff Type](https://user-images.githubusercontent.com/86383902/214368599-9c85ec7a-b5fb-407b-acc1-8581c8124ca0.png)
![Select Department Staff Type 2](https://user-images.githubusercontent.com/86383902/214368614-491ee850-bc04-43ec-b899-2a020884c363.png)
![Friend](https://user-images.githubusercontent.com/86383902/214368654-2eafc4bc-1015-4430-81e2-0a8e067dc8e3.png)

**Comment by jordanngtw** [comment]
![PIC and Facility Search 1](https://user-images.githubusercontent.com/86383902/214368811-70e59317-3944-417f-8d18-16eed6a2b7a2.png)

**Comment by Concepcion-c** [comment]
> ![PIC and Facility Search 1](https://user-images.githubusercontent.com/86383902/214368811-70e59317-3944-417f-8d18-16eed6a2b7a2.png)
![PIC and Facility Search 5](https://user-images.githubusercontent.com/121635387/214623771-a59d720a-2581-4211-9e6f-c40818f4200e.png)
