### ISSUE TITLE
[tech task] Create Dummy Roster

### ISSUE THREAD

**Issue by jordanngtw** [PublicDataWorks/complaint-manager#234]
### [Tech Task]
This story is about creating a dummy roster we can use for testing.

We will receive the headers for the roster that Hawaii uses.... soon. Until then, use the columns in the comment below.

Make 500 records (?) in csv format. 

### In Scope
1. Create roster!

### Out of Scope
1. uploading it or anything
2.
3.

### Open Questions
1.
2.
3.

### Checklist (should be reviewed before grooming as the BA or Pair are writing the card—NOT reviewed for the first time at grooming)
0. Discuss the technical implementation of this card.
1. Discuss how this feature would be included in or affect the Audit Log.
2. In respect to security, what could go wrong? Brainstorm threats using STRIDE model, especially if this card introduces a new technical architecture or design pattern. (TIMEBOX: 7 mins) https://docs.google.com/document/d/18AFl1d3SRieI4d_8R3GyEazqQOycLNDHGN_vOYIHuiE/edit#heading=h.aio9zb5j63wl
3. Ensure any open questions have been resolved with stakeholders.
4. Determine if documentation should be referenced or created.
5. Ensure to include all necessary mockups to this card.
6. Discuss what success/failure user feedback messages would be present, if any occur (front end/back end).
7. Discuss why this feature would not be implemented behind a toggle / what would happen if this card was partially done while a release branch was being cut.
8. If this card is part of a sequence of cards, discuss if this card should be blocked until the testing of previous  cards in the sequence have been finished.
9. Have we added edge cases as ACs that we're considered from a QA perspective
10. Does this card overlap with any entities outlined in [API Housekeeping](https://www.pivotaltracker.com/story/show/173963545)?  

**Notes:**

**Comment by jordanngtw** [comment]
![InkedAnnotation 2022-12-02 133534_LI](https://user-images.githubusercontent.com/86383902/207988816-fb1dde84-b5f7-44c7-b206-4a4afcf2ed66.jpg)

**Comment by andrew-rist-tw** [comment]
List of fields available in the report

Housing location (Region)
--
Housing location (Facility)
Location Sub 1
Location Sub 2
Location Sub 3
Location Sub 4
Housing location (Housing)
Current Location
Name
Inmate ID
State ID
FBI ID
Social Security No.
Status
Custody Status
Release Type
Security classification
Classification date
Booking start date
Tentative Release Date
Next court date
Next court division
Next court name
Next court judge
Booking end date
Actual release date
Weekender
Gender
Date of birth
Age
Primary ethnicity
Country of birth
Citizenship
Race
Religion
Language
Marital Status
Address
Date Death Recorded
Date of Escape
Date of recapture
Indigent
Sentence length
On Count
Trust Account Number
Account Status
Account Status Reason
Current Balance
Monies on Hold
Frozen Cash
Commissary Commitments
Other Commitments
Transfer Date
Custody Status Reason
Muster Housing Location
