### ISSUE TITLE
This Isn't the PiC I'm Looking For

### ISSUE THREAD

**Issue by jordanngtw** [PublicDataWorks/complaint-manager#236]
### Business Context:

This is a story for manually entering details for a person in custody (if they aren't in the roster yet, or someone who gets out of jail but has still submitted a complaint).

**As a** HCSOC staffer
**I want** to input a PiC even if they aren't in the roster
**So that** I can create a case and track their complaint

### In Scope
1. Add "PiC Not Found/Add Person in Custody Manually" button
2. add the complainant
4. Add the given data to the `cases_inmates` table (need to add columns for inmate_id, first_name, middle_initial, last_name, suffix, and facility)
5. Make sure an inmate added in this way is properly displayed on the case details page

Fields:
ID #, First, Last, Facility (dropdown)

### Out of Scope
1. Flagging an inmate who is not in the roster for follow-up
2.
3.

### Open Questions
1. How much is this going to happen? How do we want to count these people?
2.
3.

Steps:
1. Search for PiC
2. find nothing! then the add manually button shows up
3. click add manually
6. get taken to new page with fields for adding PiC
7. Click "add PIC to Case"
8. Land on Case Details Page

## Acceptance Criteria

1. Scenario: Add the button
Given i am on the PiC search results page
AND i don't see the PiC I'm looking for
When I click "Manually Add Person in Custody"
Then I see the manual add page

2. Scenario: Fill out the Fields
Given I am on the manual input page for PiC
When I fill out the fields
Then I can save that entry
AND i land on the case details page

**none of the fields are required**

### Checklist (should be reviewed before grooming as the BA or Pair are writing the card—NOT reviewed for the first time at grooming)
0. Discuss the technical implementation of this card.
1. Discuss how this feature would be included in or affect the Audit Log.
3. In respect to security, what could go wrong? Brainstorm threats using STRIDE model, especially if this card introduces a new technical architecture or design pattern. (TIMEBOX: 7 mins) https://docs.google.com/document/d/18AFl1d3SRieI4d_8R3GyEazqQOycLNDHGN_vOYIHuiE/edit#heading=h.aio9zb5j63wl
9. Ensure any open questions have been resolved with stakeholders.
10. Determine if documentation should be referenced or created.
11. Ensure to include all necessary mockups to this card.
12. Discuss what success/failure user feedback messages would be present, if any occur (front end/back end).
13. Discuss why this feature would not be implemented behind a toggle / what would happen if this card was partially done while a release branch was being cut.
14. If this card is part of a sequence of cards, discuss if this card should be blocked until the testing of previous  cards in the sequence have been finished.
15. Have we added edge cases as ACs that we're considered from a QA perspective
16. Does this card overlap with any entities outlined in [API Housekeeping](https://www.pivotaltracker.com/story/show/173963545)?  

**Notes:**

**Comment by Concepcion-c** [comment]
![1  PIC Search and Create](https://user-images.githubusercontent.com/121635387/220663778-ef6640bf-f59b-440a-a66c-1c7c23ee642d.png)
![2  Search Roster 1](https://user-images.githubusercontent.com/121635387/220663785-3b6a9966-40dd-49b8-a1e1-6444072c75cc.png)
![3  Search Roster 2](https://user-images.githubusercontent.com/121635387/220663787-e6444185-7bc9-44a9-9150-d90dda2757dd.png)
![4  Search Roster 3](https://user-images.githubusercontent.com/121635387/220663790-6edbeee6-4abe-466c-93bd-6f31b33fe25c.png)
![5  Search Roster 4](https://user-images.githubusercontent.com/121635387/220663793-3a6c31ce-0256-4693-af57-b36628d755c5.png)
![6  Manually Add](https://user-images.githubusercontent.com/121635387/220663797-5cf41c1f-44c5-4b63-9e77-bbb0e5f5cda8.png)
![7  Case Details - End](https://user-images.githubusercontent.com/121635387/220663802-788d6983-4b24-4768-9edc-f8602e854161.png)
