### ISSUE TITLE
Anonymous Person in Custody

### ISSUE THREAD

**Issue by jordanngtw** [PublicDataWorks/complaint-manager#243]
### Business Context:

There are cases when a person in custody who makes a complaint would wish to remain anonymous! this will take care of that. 
This will also add a notes page

**As an** investigator
**I want** to allow people to complain anonymously
**So that** we can address their concerns. 

### In Scope
1. Notes page! (notes page only has checkbox and notes field (no contact info))
2. checkbox in notes page
3. ANON tag
4. ANON tag for NOIPM too!
5.

### Out of Scope
1. Editing Inmate Details

## Acceptance Criteria

Steps:
- choose PiC
- Go to notes page
- check Anonymous box
- Add to Case

1. Scenario: Anonymous complainant
Given you are creating a case for a PiC who wishes to be anonymous
When you are in the notes page
Then you check the "anonymous" box (text: Anonymize Person in Custody in Letters)

2. Scenario: 
Given a complainant's anonymous box has been checked
When you view the case on the case dashboard 
Then it has the (ANON) tag prepended (see screenshots)

### Checklist (should be reviewed before grooming as the BA or Pair are writing the card—NOT reviewed for the first time at grooming)
0. Discuss the technical implementation of this card.
1. Discuss how this feature would be included in or affect the Audit Log.
2. In respect to security, what could go wrong? Brainstorm threats using STRIDE model, especially if this card introduces a new technical architecture or design pattern. (TIMEBOX: 7 mins) https://docs.google.com/document/d/18AFl1d3SRieI4d_8R3GyEazqQOycLNDHGN_vOYIHuiE/edit#heading=h.aio9zb5j63wl
3. Ensure any open questions have been resolved with stakeholders.
6. Determine if documentation should be referenced or created.
7. Ensure to include all necessary mockups to this card.
8. Discuss what success/failure user feedback messages would be present, if any occur (front end/back end).
9. Discuss why this feature would not be implemented behind a toggle / what would happen if this card was partially done while a release branch was being cut.
10. If this card is part of a sequence of cards, discuss if this card should be blocked until the testing of previous  cards in the sequence have been finished.
11. Have we added edge cases as ACs that we're considered from a QA perspective
12. Does this card overlap with any entities outlined in [API Housekeeping](https://www.pivotaltracker.com/story/show/173963545)?  

**Notes:**

**Comment by Concepcion-c** [comment]
![PiC Unknown 1](https://user-images.githubusercontent.com/121635387/219743795-c6afd8fc-bb63-4b27-bfcf-f5cbf9274632.png)
![PiC Unknown 2](https://user-images.githubusercontent.com/121635387/219743799-fdb51373-b859-490f-967f-8b930aeb2b1d.png)

**Comment by Concepcion-c** [comment]
@jordanngtw Adding updated designs to match updates from last tue's meeting

**Comment by Concepcion-c** [comment]
![Friend](https://user-images.githubusercontent.com/121635387/223226138-00776dee-c070-4795-b56c-bd5170b095a0.png)
![PiC Known Anon](https://user-images.githubusercontent.com/121635387/223226172-9d167e22-4d03-4bb6-8ea3-018529fd99bd.png)

**Comment by Concepcion-c** [comment]
Next Round:


![Image](https://user-images.githubusercontent.com/121635387/224149362-f6b9128d-45f2-4dce-9a45-71b987fa4bab.png)
![Image](https://user-images.githubusercontent.com/121635387/224149366-034cb18b-8d5f-4b6f-b7b5-cbbc54752972.png)
![Image](https://user-images.githubusercontent.com/121635387/224149365-8814ca99-3851-433f-954e-703c57e40660.png)
![Image](https://user-images.githubusercontent.com/121635387/224149367-8bb3f813-52ea-4a92-8f8f-e3967daed0a8.png)
![Image](https://user-images.githubusercontent.com/121635387/224149364-29c225ec-de68-43fd-a58f-c95bab1c0250.png)
![Image](https://user-images.githubusercontent.com/121635387/224149363-03a98f43-98c3-4627-9190-804a11fe6450.png)
![Image](https://user-images.githubusercontent.com/121635387/224149370-f9e3c90d-b1f6-491f-94fa-da245919af06.png)

**Comment by Concepcion-c** [comment]
@andrew-rist-tw @jordanngtw see last frame. tiny mod to allow the user to check anonymity on the same page as all the other details. Should be a simple yes or no here

**Comment by andrew-rist-tw** [comment]
This is what we do for NO (add (AC) in front), but yours is more verbose, but also hidden by the expansion panel

![Image](https://user-images.githubusercontent.com/85584869/224157896-5e950fbf-d2ca-4d44-b6b4-063afe7bd6fa.png)

**Comment by Concepcion-c** [comment]
Ok, I was wondering what the (AC) meant as I was playing with it. Anyway that we can change it to (Anon) in front?

**Comment by andrew-rist-tw** [comment]
That makes sense to me. @jordanngtw would you want Anon to be used for NO as well as Hawaii?

**Comment by Concepcion-c** [comment]
![Image](https://user-images.githubusercontent.com/121635387/224373722-0e494b9d-2a27-4410-bfdb-0ed122887308.png)
![Image](https://user-images.githubusercontent.com/121635387/224373718-c82911ae-10a1-4d60-9bf6-89f37d00fab4.png)
![Image](https://user-images.githubusercontent.com/121635387/224373723-09ac13e1-c275-4be3-ac24-8764e7372cdf.png)
![Image](https://user-images.githubusercontent.com/121635387/224373717-2176acf5-2b27-4a22-b063-b4cc41b0c2e6.png)
![Image](https://user-images.githubusercontent.com/121635387/224373719-f0437f0a-edbc-4e14-9262-55bf1f604a45.png)
![Image](https://user-images.githubusercontent.com/121635387/224373721-2f47e39a-758a-4279-b4f5-fd144a33b424.png)
![Image](https://user-images.githubusercontent.com/121635387/224373720-6e1df432-1145-4bfe-835d-bc0b20231e8a.png)

**Comment by Concepcion-c** [comment]
![Image](https://user-images.githubusercontent.com/121635387/226969157-12b02ff6-dfc8-40a7-ad78-bffead1303de.png)
![Image](https://user-images.githubusercontent.com/121635387/226969156-239a43d5-3d73-404e-8065-deb063d5cfb7.png)
![Image](https://user-images.githubusercontent.com/121635387/226969155-1715ca5d-1753-456a-a283-abaa51379e66.png)
![Image](https://user-images.githubusercontent.com/121635387/226969160-9592aa05-b66c-4f76-aca3-6c8212cf5807.png)
![Image](https://user-images.githubusercontent.com/121635387/226969161-0005b50b-1eb9-4bc3-92c9-60a86a1ad4d7.png)
![Image](https://user-images.githubusercontent.com/121635387/226969158-22324d48-998d-45c7-9ac1-3c23503e4881.png)
![Image](https://user-images.githubusercontent.com/121635387/226969159-82f1a96d-e90c-400e-92c1-73d4dfa0940c.png)
