### ISSUE TITLE
Update NOPD Roster

### ISSUE THREAD

**Issue by jordanngtw** [PublicDataWorks/complaint-manager#262]
### Business Context:
I want to be able to use the updated roster to find and accuse officers

**As a** new orleans user
**I want** to search the updated roster of officers
**So that** I can find the officer i'm looking for

### In Scope
1. Upload new roster
2. ONLY FOR NOIPM PROD (awsnoipm in 1password)
3. Tweak the script (if necessary)
4. Ask Andrew or Jordan for the roster so it's not on github for the public to see
5. Replicate the seeder that runs the upload job so the job is run again

### Out of Scope
1. 
2.
3.

### Open Questions
1.
2.
3.

### Checklist (should be reviewed before grooming as the BA or Pair are writing the card—NOT reviewed for the first time at grooming)
- [ ] Ensure to include all necessary mockups to this card.
- [ ] Discuss what success/failure user feedback messages would be present, if any occur (front end/back end).
- [ ] Discuss Feature Flag: Where could a development flag go to flag off incomplete work? Do we want to keep the flag long-term?
- [ ] If this card is part of a sequence of cards, discuss if this card should be blocked until the testing of previous cards in the sequence have been finished.
- [ ] Have we added edge cases as ACs that we're considered from a QA perspective
- [ ] Should the new functionalities be offered only to users with certain permissions?
- [ ] How should this functionality differ between different orgs, and if it does differ, what is the hinge point we should use for that functionality?

**Notes:**

**Comment by andrew-rist-tw** [comment]
Script = `src/server/seeder_jobs/createSeedOfficerDataFromS3.js`

**Comment by gumidyal** [comment]
1. compare current officer csv to new roster to assess how each field in the new roster will correspond with the fields in the database.
- workStatus field will be either "Active" or "Terminated (note: termination dates of “1900-01-01” mean the officer is still employed)
- endDate, DOB, windowsUsername are in the old roster but not the new one
- WorkLocation field has been changed to two fields titled Bureau or Assignment
2. assess the changes from old roster to new and how those changes will impact the script
3. upload dummy file to local to test the script
4. update script as necessary
5. check script in each environment except prod
6. upload new roster to s3 to be used in prod
