### ISSUE TITLE
Upgrade to v3 of AWS SDK

### ISSUE THREAD

**Issue by andrew-rist-tw** [PublicDataWorks/complaint-manager#264]
### Business Context:
V2 of the AWS SDK is going into maintenance mode some time this year, and we need to upgrade to [v3, which splits the different services into different libraries](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/welcome.html). This will require finding all the places where `aws-sdk` is imported or required and replacing it with the appropriate v3 library or libraries

**As a** Complaint Manager
**I want** to use the most up to date AWS SDK package so that 
**So that** I can have the benefit of regular updates that will solve security issues and stay in sync with AWS services

### In Scope

1. Remove `aws-sdk` from package.json
2. Add new v3 packages to package.json (definitely s3 and secrets-manager, look around to see if there are more)
3. Replace uses of `aws-sdk` with the appropriate v3 library

### Out of Scope

1.

### Open Questions

1.

### Checklist (should be reviewed before grooming as the BA or Pair are writing the card—NOT reviewed for the first time at grooming)

- [x] Ensure to include all necessary mockups to this card.
- [x] Discuss what success/failure user feedback messages would be present, if any occur (front end/back end).
- [x] Discuss Feature Flag: Where could a development flag go to flag off incomplete work? Do we want to keep the flag long-term?
- [x] If this card is part of a sequence of cards, discuss if this card should be blocked until the testing of previous cards in the sequence have been finished.
- [x] Have we added edge cases as ACs that we're considered from a QA perspective
- [x] Should the new functionalities be offered only to users with certain permissions?
- [x] How should this functionality differ between different orgs, and if it does differ, what is the hingepoint we should use for that functionality?

**Notes:**

**Comment by sbhamani** [comment]
Auto migration/transformation from aws sdk v2 to v3 in JS: https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html
