### ISSUE TITLE
Create a section for the report banner and Hawaii values

### ISSUE THREAD

**Issue by mariliasoaresTW** [PublicDataWorks/complaint-manager#290]
### Dependency: 
Story #288 to be done

### Business Context:
I want to display the banner with the public report and the Hawaii values below the navigation menu.

### In Scope
1. Create a banner for the section with the annual report link, with the images and copy provided on the mockups
- Link for the report: https://hcsoc.hawaii.gov/wp-content/uploads/2023/01/2022-HCSOC-Annual-Report-FINAL.pdf 
- Banner hero image: https://github.com/PublicDataWorks/instance_files_hawaii_csoc/blob/main/Images/Hawaii-Hero_banner.png

2. Create the "values" section 
- Icons: https://github.com/PublicDataWorks/instance_files_hawaii_csoc/commit/14119736c465de2dab26e10e29ab11bd415366a0

3. The copy for the banner should be the one on the wireframes.

All above should be done for the 3 breakpoints supported: mobile, desktop, tablet. Note that in mobile the values section has the icons shrunk to fit the space.

### Out of Scope
1.
2.
3.

## Acceptance Criteria

1. Scenario: 
Given I navigate to the Hawaii website
Then I see a banner with the hero image, the text description and the link to the anual report

### Mockups

https://www.figma.com/file/SHMDMgzr7damRoT12ToEz5/Hawaii-CSOC-Advocacy--2?type=design&node-id=265-3755&t=ODfe3QQ4Bzg1AmxQ-0

### Checklist (should be reviewed before grooming as the BA or Pair are writing the card—NOT reviewed for the first time at grooming)
- [X] Ensure to include all necessary mockups to this card.
- [X] Discuss what success/failure user feedback messages would be present, if any occur (front end/back end).
- [X] Discuss Feature Flag: Where could a development flag go to flag off incomplete work? Do we want to keep the flag long-term?
- [X] If this card is part of a sequence of cards, discuss if this card should be blocked until the testing of previous cards in the sequence have been finished.
- [X] Have we added edge cases as ACs that we're considered from a QA perspective
- [X] Should the new functionalities be offered only to users with certain permissions?
- [X] How should this functionality differ between different orgs, and if it does differ, what is the hinge point we should use for that functionality?

**Notes:**

**Comment by andrew-rist-tw** [comment]
Media-Query Breakpoints
mobile: 360px max-width
tablet: 834px max-width
desktop: 1920px max-width

**Comment by andrew-rist-tw** [comment]
Media Queries with React/MUI - https://mui.com/material-ui/react-use-media-query/
