### ISSUE TITLE
Enable write in option for directives

### ISSUE THREAD

**Issue by mariliasoaresTW** [PublicDataWorks/complaint-manager#291]
### Business Context:
I want to enable directives on chapter's allegations to be added manually, similar to what we enabled on #272

As an NOIPM employee
I want to be able to add new NOPD directives when adding an officer allegation
So that I don't have to do a workaround when there's no existing directive I want to add that isn't in the list

### In Scope
1. Update officers-allegations handler to accept directives that weren't already created (by allowing to write in a directive and linking it to a chapter) - database schema updates - this will require a new directive table to be created.
2. Creating a directive dropdown on the allegations page with the existing directives. 
3. On the same dropdown, allow users to add new directives by writing in - same behavior as adding a new chapter.
4. Display the selected directive in the expansion panel of the added allegation

### Out of Scope - to be done on #294
1. Update the search to remove the directive keyword search and allow searching only by selecting a rule or paragraph, using the existing dropdown list.

2. Update the db to remove the directives column on the allegations table and remove it from the table on the frontend

## Acceptance Criteria

1. Scenario: 
Given I am adding and allegation to a case
When I select a rule 
Then I can select a directive for the allegation from the drop down OR add a new directive by writing them in

### Checklist (should be reviewed before grooming as the BA or Pair are writing the card—NOT reviewed for the first time at grooming)
- [ ] Ensure to include all necessary mockups to this card.
- [ ] Discuss what success/failure user feedback messages would be present, if any occur (front end/back end).
- [ ] Discuss Feature Flag: Where could a development flag go to flag off incomplete work? Do we want to keep the flag long-term?
- [ ] If this card is part of a sequence of cards, discuss if this card should be blocked until the testing of previous cards in the sequence have been finished.
- [ ] Have we added edge cases as ACs that we're considered from a QA perspective
- [ ] Should the new functionalities be offered only to users with certain permissions?
- [ ] How should this functionality differ between different orgs, and if it does differ, what is the hinge point we should use for that functionality?

**Notes:**

**Comment by andrew-rist-tw** [comment]
You'll want to check the letter template as well, since it may change the template value for directive in the letter

**Comment by andrew-rist-tw** [comment]
I added a directives.csv to localstack-seed-files in instance-files-noipm, so it should auto-load into localstack when you do an down and up with noipm instance files, but I didn't upload it to s3 (we'll need to put it in noipm-seed-files in both our account and NO's account eventually) so that if there are any changes necessary they can be made in instance-files before uploading
