### ISSUE TITLE
Staffing shortage stats

### ISSUE THREAD

**Issue by mariliasoaresTW** [PublicDataWorks/complaint-manager#292]
### Business Context:
 I want see info and statistics on staffing shortage on Hawaii CSOC website so I can be informed on the critical conditions reg. staffing

### In Scope
1. Create the Staffing Shortage - Overall Impression section on the Hawaii website, including the static map and data on capacity. 

2. This section will be placed below the "data dashboard" section which won't exist yet.

Note: Those numbers will be hardcoded at the moment. The numbers on the hi-fi design are correct. 

### Out of Scope
1. Dynamic map
2. Data calculations

## Acceptance Criteria

1. Scenario: 
Given I go to /public-data using mobile, tablet or desktop
Then I the staffing shortage section with the info regarding overcrowding in prisons and jails, the map with Hawaii's prisons and jails location and the statistics on overcrowding.

### Mockups
https://www.figma.com/file/SHMDMgzr7damRoT12ToEz5/Hawaii-CSOC-Advocacy--2?type=design&node-id=265-3755&t=ODfe3QQ4Bzg1AmxQ-0

### Assets

https://github.com/PublicDataWorks/instance_files_hawaii_csoc/tree/main/Images

- Hawaii-map-prison.png  (img alt text: “Map of Hawaii’s correctional facilities, 4 prisons and 4 jails”)
- Hawaii-map-prisonSM.png (img alt text: “Map of Hawaii’s correctional facilities, 4 prisons and 4 jails”
- MenPriscon_stockIMg.jpg
(img alt text: “Limits out-of-cell time for people in custody (in unit and outdoor recreation).“”Serious overcrowding attributing to inhumane conditions, specifically for jails”)

### Checklist (should be reviewed before grooming as the BA or Pair are writing the card—NOT reviewed for the first time at grooming)
- [ ] Ensure to include all necessary mockups to this card.
- [ ] Discuss what success/failure user feedback messages would be present, if any occur (front end/back end).
- [ ] Discuss Feature Flag: Where could a development flag go to flag off incomplete work? Do we want to keep the flag long-term?
- [ ] If this card is part of a sequence of cards, discuss if this card should be blocked until the testing of previous cards in the sequence have been finished.
- [ ] Have we added edge cases as ACs that we're considered from a QA perspective
- [ ] Should the new functionalities be offered only to users with certain permissions?
- [ ] How should this functionality differ between different orgs, and if it does differ, what is the hinge point we should use for that functionality?

**Notes:**
Look into MUI's Container to hold the cards. Should already be responsive.
Media-Query Breakpoints
mobile: 360px max-width
tablet: 834px max-width
desktop: 1920px max-width

**Comment by kjonesthoughtworks** [comment]
I have upload the static map in Github (image folder) called Hawaii Map-Prison.png. The content was taken from Annual report on page 103. https://hcsoc.hawaii.gov/wp-content/uploads/2023/01/2022-HCSOC-Annual-Report-FINAL.pdf

Chinwe is proofreading and validating content. I will check with her on the status
