### ISSUE TITLE
Enable write in option for case notes

### ISSUE THREAD

**Issue by isabelolson** [PublicDataWorks/complaint-manager#300]
### Business Context:
I want to enable case note actions on the case details page to be added manually, similar to what we enabled on https://github.com/PublicDataWorks/complaint-manager/issues/272 and https://github.com/PublicDataWorks/complaint-manager/issues/291 (for both NOIPM **AND** Hawaii)

As an NOIPM and Hawaii employee
I want to be able to add new case note actions when adding a case note
So that I don't have to do a workaround when there's no existing action I want to add that isn't on the list

### In Scope
1. Update handler to accept actions that weren't already created (by allowing to write in an action and linking it to a case note).
2. Change "Action Taken" dropdown on the `CaseNoteDialog` into a `CreatableDropdown` that lets users add new ones.
3. ~~Do not store the manually created action taken.~~ **Do** store the manually created action taken.
5. Ensure that "Add Case Note" is logged the audit export
### Out of Scope
1. Update the current list of case actions to remove NOIPM specific actions (this will be generalized later on). 

### Mockups
<img width="511" alt="Screenshot 2023-07-17 at 3 20 10 PM" src="https://github.com/PublicDataWorks/complaint-manager/assets/82597827/6add3d64-73e2-444e-84b2-784c940a7fb6">

## Acceptance Criteria

1. Scenario: 
Given I am adding a case note to a case
When I select an action 
Then I can select an action from the drop down OR add a new action by writing them in

2. Scenario: 
Given I am editing a case note on a case
When I select an action 
Then I can select an action from the drop down OR add a new action by writing them in

### Checklist (should be reviewed before grooming as the BA or Pair are writing the card—NOT reviewed for the first time at grooming)
- [ ] Ensure to include all necessary mockups to this card.
- [ ] Discuss what success/failure user feedback messages would be present, if any occur (front end/back end).
- [ ] Discuss Feature Flag: Where could a development flag go to flag off incomplete work? Do we want to keep the flag long-term?
- [ ] If this card is part of a sequence of cards, discuss if this card should be blocked until the testing of previous cards in the sequence have been finished.
- [ ] Have we added edge cases as ACs that we're considered from a QA perspective
- [ ] Should the new functionalities be offered only to users with certain permissions?
- [ ] How should this functionality differ between different orgs, and if it does differ, what is the hinge point we should use for that functionality?

**Notes:**

**Comment by mariahsager-tw** [comment]
`CaseTagDialog` should be one example where this sort of thing is already set up

**Comment by heliofreitastw** [comment]
we did code review on February 12 2024

**Comment by thoughtworks-vwong** [comment]
Verified write-in option for case notes is working as expected.

NO Staging

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/e480a33d-c201-4908-b2a9-19a281b4c639

Hawaii Staging

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/90f081d9-d152-4723-9fff-9cfe6fc10360
