### ISSUE TITLE
[SPIKE] Share button: integration with Facebook, Twitter, Instagram, Email

### ISSUE THREAD

**Issue by mariliasoaresTW** [PublicDataWorks/complaint-manager#301]
Investigate how to allow users to share graphs on social media and how the integration with the following platforms work:
- Instagram
- Facebook
- Twitter
- Email
- Url (link) to the page

See reference from other pages on Figma Data Visualization https://www.figma.com/file/SHMDMgzr7damRoT12ToEz5/Hawaii-CSOC-Advocacy--2?type=design&node-id=65-2607&mode=design

Timebox: 3 days

**Comment by isabelolson** [comment]
Findings: https://docs.google.com/document/d/1APFPd7z3blnafNAwpQzq3qCCHNrXSSsWxIx_RY_C8lY/edit?usp=sharing
