### ISSUE TITLE
TW banner and page footer

### ISSUE THREAD

**Issue by mariliasoaresTW** [PublicDataWorks/complaint-manager#306]
Create the TW banner and page footer to finish MVP for Hawaii public page

### Business Context:
I want to display the TW partnership banner and a footer on the Hawaii's public page.

### In Scope
1. Include the TW banner on the bottom of the page
2. Below the banner, include the footer with links as specified on the mockups.

Links:

Banner (contributor partner): https://www.thoughtworks.com/about-us/social-change

About us: https://hcsoc.hawaii.gov/about-us/
Contact us: https://hcsoc.hawaii.gov/contact-us/
Terms of Use: https://portal.ehawaii.gov/page/terms-of-use/
Accessibility: https://portal.ehawaii.gov/page/accessibility/
2023 Privacy Policy:  https://portal.ehawaii.gov/page/privacy-policy/
Designed and developed in partnership with Thoughtworks:  https://www.thoughtworks.com/

## Acceptance Criteria

1. Scenario: 
Given I go to /public-data using mobile, tablet or desktop
Then I see the TW banner on the page
And I can click on the banner and opens the TW website on a new tab  (https://www.thoughtworks.com/about-us/social-change)

2. Scenario:
Given I go to /public-data using mobile, tablet or desktop
Then I see a footer on the bottom of the page
And I can click on the links which opens the pages on a new tab.

### Mockups
Link to the figma mockups
https://www.figma.com/file/SHMDMgzr7damRoT12ToEz5/Hawaii-CSOC-Advocacy--2?type=design&node-id=428%3A3237&mode=design&t=UZP5VFPI8pVjkP6G-1

You can find Desktop/Tablet/Mobile View in the Dev Handoff Section

### Checklist (should be reviewed before grooming as the BA or Pair are writing the card—NOT reviewed for the first time at grooming)
- [ ] Ensure to include all necessary mockups to this card.
- [ ] Discuss what success/failure user feedback messages would be present, if any occur (front end/back end).
- [ ] Discuss Feature Flag: Where could a development flag go to flag off incomplete work? Do we want to keep the flag long-term?
- [ ] If this card is part of a sequence of cards, discuss if this card should be blocked until the testing of previous cards in the sequence have been finished.
- [ ] Have we added edge cases as ACs that we're considered from a QA perspective
- [ ] Should the new functionalities be offered only to users with certain permissions?
- [ ] How should this functionality differ between different orgs, and if it does differ, what is the hinge point we should use for that functionality?

**Notes:**
Media-Query Breakpoints
mobile: 360px max-width
tablet: 834px max-width
desktop: 1920px max-width

**Comment by sbhamani** [comment]
To make a link open in a new tab, add `target="_blank"` to the <a> tag
