### ISSUE TITLE
Add /public-data to existing HCSOC domain

### ISSUE THREAD

**Issue by mariliasoaresTW** [PublicDataWorks/complaint-manager#309]
-> Pending confirmation from Christin

1. Work with George to include the /public-data to the existing website domain https://hcsoc-data.hawaii.gov/

2. Add the new page (https://hcsoc-data.hawaii.gov/public-data) to the sitemap 

https://hcsoc.hawaii.gov/wp-sitemap.xml

**Comment by sbhamani** [comment]
Need to jump on a call with Christin/George to add the new URL to their sitemap. Not sure if this includes adding the actual link on their wordpress site for users to start clicking.

**Comment by mariliasoaresTW** [comment]
No need to add the URL to current sitemap - we should actually create our own, for our subdomain. This is on this card https://github.com/PublicDataWorks/complaint-manager/issues/362
