### ISSUE TITLE
Manifest.json failed request on login

### ISSUE THREAD

**Issue by mariliasoaresTW** [PublicDataWorks/complaint-manager#318]
**Describe the bug**
There is a console error for manifest.json that shows up when trying to go to /login

**To Reproduce**
1. Go to https://noipm-ci.herokuapp.com or https://noipm-staging.herokuapp.com
2. Look at the network requests and you will see a manifest.json error

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/67479313/5a45172a-acc3-483c-a432-db645f465102)

Notes: we didn't identify any unusual behavior on the app due to this error, but we should investigate it.

**Expected behavior**
No console errors when going to /login

**Comment by mariliasoaresTW** [comment]
This might be resolved by #317

**Comment by thoughtworks-vwong** [comment]
Verified error is no longer displayed on login

Hawaii

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/5ca6154f-7278-4ffc-b0a9-394d251e035d

NO

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/e832277f-71ef-4825-88c2-b19504cfe21b
