### ISSUE TITLE
Error when hitting the back button after login

### ISSUE THREAD

**Issue by mariliasoaresTW** [PublicDataWorks/complaint-manager#321]
**Describe the bug**
When you hit the back button right after logging in you get an error message stating that you are already logged in

![Image](https://user-images.githubusercontent.com/67479313/260573941-f5c4dcc1-2098-4c2d-bc3b-5b4960592e3a.png)

**To Reproduce**
1. Login 
2. On the home page hit the back button
3. You will get an error message on the page

**Expected behavior**
If the Okta session is still valid and you are on the home page you should go back to login page when you hit the back button, without any auth SDK msg.

- [ ] Look into Okta folder in complaint manager 
- [ ] App.js handles routing from okta login to main page 
- [ ] Hawaii instance files holding routes 
- [ ] console.log history to see history of routing

**Comment by faraakhatTW** [comment]
Looking into this conversation might help to understand the issue and also possibly find the solution -> https://github.com/okta/okta-oidc-js/issues/898

**Comment by faraakhatTW** [comment]
In `App.js` need condition is added and it is currently triggering on back button. Just need to figure out how to redirect properly to `/logout` or `okta` login page
![Image](https://github.com/PublicDataWorks/complaint-manager/assets/136751291/d02a5381-dbdf-4413-85db-f009055950f7)

**Comment by thoughtworks-vwong** [comment]
Verified error no longer appears when hitting the back button after login on Hawaii. Also double checked on NO and no 

Hawaii

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/fb219972-7749-4597-bf07-0ea56a30b93e

NO

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/45b86675-9222-4747-8e75-604b4c61a72a
