### ISSUE TITLE
[Chore] Rotate more AWS keys

### ISSUE THREAD

**Issue by sbhamani** [PublicDataWorks/complaint-manager#325]
TW Vulnerabilities scanner found these 3 AWS keys we need to rotate as it has been over 180 days since they were last rotated.

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/34656317/f9550561-2396-4e2c-944a-80a6088fd320)

How To:
https://sites.google.com/thoughtworks.com/tw-invisible-institute-wiki/development-resources/environment-variables#h.t5hefl7iq40u

**Comment by isabelolson** [comment]
Rotated terraform and noipm-local. The noipm-local keys must be updated in each individuals local configuration file. noipm-production was set to inactive (which will soon be deleted if no issues occur).
