### ISSUE TITLE
Myths and facts - design updates

### ISSUE THREAD

**Issue by mariliasoaresTW** [PublicDataWorks/complaint-manager#326]
Design updates for the Myths and Facts section

1. Myths are a title and have a dif color background than the facts session.
2. Numbering for each myth 
3. Some keywords on the text are highlighted in teal 

Mockups:

https://www.figma.com/file/SHMDMgzr7damRoT12ToEz5/Hawaii-CSOC-Advocacy--2?type=design&node-id=2276-8909&mode=design&t=rwTqW0RudfcPsLJS-4

**Comment by claireholt-tw** [comment]
- [ ] Add numbers
- [ ] Change the color of "Myth" and the number
- [ ] Change background color of fact section
- [ ] Highlight keywords
- [ ] Font sizes and spaces for everything
