### ISSUE TITLE
Replace to wit list in prod with the one from staging

### ISSUE THREAD

**Issue by sbhamani** [PublicDataWorks/complaint-manager#330]
[rule_chapters_202310301354.csv](https://github.com/PublicDataWorks/complaint-manager/files/13219324/rule_chapters_202310301354.csv)

Update the `rules_chapter `table with the data current rules as per the attached csv file, both in staging and prod.

Make sure the data doesn't get wiped out when we release (update seeder).

**Comment by mariliasoaresTW** [comment]
I've sent an email to Christian today to confirm we have the correct values before we make this update. https://docs.google.com/spreadsheets/d/1Xkd5zeYUJ_1rDVCTPZmF-zUVJhS99pPETu7LVDoCZhY/edit#gid=0

**Comment by mariliasoaresTW** [comment]
CSV file with updates - PROD:



[rules_chapter PROD - Sheet1.csv](https://github.com/PublicDataWorks/complaint-manager/files/13300887/rules_chapter.PROD.-.Sheet1.csv)
