### ISSUE TITLE
Change write-in directives saving mechanism

### ISSUE THREAD

**Issue by sbhamani** [PublicDataWorks/complaint-manager#331]
Currently in NO, when you add a write-in directive, they are saved globally. However, we do not want the manually created directives to be saved on the db, as the list is getting too long. 

**In Scope**
1. Change the saving mechanism for directives created through write-in so they won't be saved anymore
2. Maintain the ability to write in directives if the user wants it.

**ACs**

When I write in a new directive 
Then this manually created directive is not saved on the database

When I select an existing directive from the drop down
Then that directive continues to exist in the db

**Comment by mariliasoaresTW** [comment]
@mariliasoaresTW to check with Christian if we should NOT store the write-in directive at all OR store and attach it to the chapter.

**Comment by mariliasoaresTW** [comment]
We confirmed with Christian we do not want to save manually created directives
