### ISSUE TITLE
Fix prod pipeline step "migrate production database"

### ISSUE THREAD

**Issue by sbhamani** [PublicDataWorks/complaint-manager#335]
**Describe the bug**
When the deploy pipeline gets to the deploy-production-noipm stage, at the "migrate production database" step, if we fail to connect to S3 and get an Access Denied error, the pipeline still moves forward successfully. We should also check this for the hawaii stage.

**Expected behavior**
We need to cleanly fail the pipeline when we get Access Denied in AWS S3

**Comment by thoughtworks-vwong** [comment]
Verified fix is working as expected. Please see testing results from #340
