### ISSUE TITLE
Investigate how to set up the pipeline gatekeeper when there is any type of fail!

### ISSUE THREAD

**Issue by faraakhatTW** [PublicDataWorks/complaint-manager#340]
Further information can be found in this ticket  #335

**Comment by heliofreitastw** [comment]
Given the problem we are fixing in this story is hard to find examples of when it happens. We decided to add some context and links about how we tested: 
We went to the AWS S3 and renamed a file. Initially we renamed the chapters.csv file which is used in NO. Then we trigged the deploy no NO in CI. This is the link for the deploy job: 
https://app.circleci.com/pipelines/github/PublicDataWorks/complaint-manager/2538/workflows/373d044e-1e2c-4c9c-aa94-db1e02bd41eb/jobs/19946

We saw that there was a log of an error, but the Migrate and seed DB step itself did not fail. 

We renamed another file. That is used in both orgs, so we could validate the error happening in either org. The file was the priority_levels.csv.
Then, we updated the code and pushed the change. 
The pipeline failed when deploying to HI: 
https://app.circleci.com/pipelines/github/PublicDataWorks/complaint-manager/2539/workflows/c2ab6434-1052-4192-825b-dc3d5f0b54e2/jobs/19959

Finally, we renamed all the files to their original name and rerun the deploy. Now the deploy passed. 
https://app.circleci.com/pipelines/github/PublicDataWorks/complaint-manager/2539/workflows/f14bc80b-2426-4332-b86b-c9afce162528/jobs/19960

We tested local as well for both orgs and it worked.

**Comment by rnair-tw** [comment]
for QA, @heliofreitastw to go through w/ @thoughtworks-vwong

**Comment by thoughtworks-vwong** [comment]
Verified fix is working as expected.

After renaming priority_levels.csv file to priority_levelstest.csv

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/134408135/b752bf2c-19be-497e-89f3-403bba8116c5)

After renaming file back to original name

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/134408135/26876e49-6ba4-47e6-8aca-cae4520d841c)

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/134408135/8e3090ad-e8da-47ad-93a5-62ba0d8c2a77)
