### ISSUE TITLE
Add priority incident, priority level and priority reasons to Edit Incident Details dialog

### ISSUE THREAD

**Issue by mariliasoaresTW** [PublicDataWorks/complaint-manager#344]
We would like to add a field to set up a priority for the complaints received in the system. Hawaii often receives priority 1 complaints that need more attention than other ones. We will also have this feature available for NOIPM, so they can also use it if needed.

**In Scope**

1. On the Intake Source field add a new value as  _Priority Incident_
2. When Priority Incident is selected we should display a new field for _priority level_, as a drop down with values [Priority One, Priority Two, Priority Three] 
3. Add a new drop down for _priority reasons_ with values below, in alphabetic order . This field is also only displayed when _Priority Incident_ is selected as an intake source. 

**In Scope**
1. Writing in priority reason

Death in Custody
Death of On-Duty Staff
Escape
Major Property Damage
Assault to Employee
Assault to PiC
Assault to Civilian
Significant Discovery of Contraband
Arrest of Staff
Arrest of Civilian
Disturbance/Riot
Discharge of Firearm
Hostage/Barricade
Suicide Attempt
Successful Suicide
High Risk Motor Vehicle Pursuit
Bomb Threat
PREA
Other

**Out of Scope**
 1. The case details page should also display the Priority Level and Priority Reason for that case.

**Mockups** 
https://www.figma.com/file/3XcaCKS0xC3U0mo98B8eTV/Features-Complaint-Manager?type=design&node-id=253-1284&mode=design&t=ixtXcasWcyqTUyqw-4

**ACs**

Given I have accessed the complaint manager for Hawaii
When I create a new case
Then I can select Intake Source = Priority Incident, I can select a Priority Level and a Priority Reasons for that case.

- [x] Add Priority Reasons to a redux state 
- [ ] Add foreign key into cases table for priority reason and level 
- [ ] Check CI Migration 
- [ ] Add validate to Priority Reasons and Level field ->  (*required)

**Comment by kjonesthoughtworks** [comment]
I created a mock up "New Case form" to added a field to set up a priority for the complaints. See mock up for review

https://www.figma.com/file/3XcaCKS0xC3U0mo98B8eTV/Features-Complaint-Manager?type=design&node-id=188-1567&mode=design

**Comment by mariliasoaresTW** [comment]
@kjonesthoughtworks 

Christin's feedback:


Instead of checkboxes, can we add, “Priority Incident” as a category under “Intake Source”
Once Priority Incident is chosen, can the next two dropdown boxes change?
Select a Complaint Type à Priority Level
Person in Custody à Incident Type
Priority Level should be a drop box with the following categories:
Priority One
Priority Two
Priority Three
Incident Type will be a drop box of the same list I gave you (that is listed on the screenshot).
 

Please note that the list of incidents that I gave you is specifically for Priority One’s. We are not currently receiving Priority Two or Three’s (at least not yet due to capacity). I imagine some of the categories will change for the lower priority levels, but I could get you that list so we can add in Priority Two’s and Priority Three’s at a later time? Let me know if it makes more sense to give it to you sooner.

**Comment by mariliasoaresTW** [comment]
**Open Questions**

-> Mockups for displaying these fields on the case details page  @kjonesthoughtworks

**Comment by thoughtworks-vwong** [comment]
For the priority reasons dropdown, it should also allow you to write in text in case you need to add other values.

**Comment by thoughtworks-vwong** [comment]
Hawaii Staging

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/487540d9-5695-451a-bcdd-73d89a175477

**Comment by thoughtworks-vwong** [comment]
NO Staging

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/f9671141-7b84-44df-abb2-4145f8a1a725
