### ISSUE TITLE
Investigate what to replace Postman test with

### ISSUE THREAD

**Issue by sbhamani** [PublicDataWorks/complaint-manager#347]
### Context
This is a spike card to figure out what to replace letter-generation-testing-ci postman test with, since we can no longer use postman. The outcome of this card it create an ADR.

### Timebox
Have a checkpoint on 2/29

**Comment by rnair-tw** [comment]
For @sbhamani and @thoughtworks-vwong to discuss

**Comment by thoughtworks-vwong** [comment]
Currently researching tools and I will also be speaking to my QA team and QA manager and ask for their input.

**Comment by thoughtworks-vwong** [comment]
- Primarily written in Java
- Has built in library that already handle API calls
- Designed for testing RESTful APIs
- Use standard HTTP methods (GET, POST, PUT, DELETE)
- Allow for flexible data formats, such as JSON or XML
- Can take advantage of HTTP caching mechanisms to improve performance and reduce server load
- REST APIs can be secured using standard HTTP authentication mechanisms like OAuth or API keys, as well as HTTPS encryption for secure data transmission
- Great community support + extensive documentation

**Comment by rnair-tw** [comment]
@thoughtworks-vwong to have a meeting w/ @sbhamani to discuss another framework today

**Comment by thoughtworks-vwong** [comment]
<google-sheets-html-origin><style type="text/css"></style>
Feature | Jest | Vitest
-- | -- | --
Focus | Primarily unit testing, supports other types | Primarily unit testing, limited native support for E2E
Framework Integration | Requires separate configuration | Seamless integration with Vite configuration
Built-in features | Requires additional libraries for assertions and mocks | Includes Chai assertions and Tinyspy for mocks and stubs
API | More complex API | Simpler and cleaner API
Speed | Fast, but Vitest generally considered faster, especially in watch mode | Extremely fast, particularly for watch mode re-runs
Community and Support | Large and established community, extensive documentation and resources | Growing community, active development, but less established resources compared to Jest
Maturity | Mature and well-established | Newer framework, still under development
Compatibility | Wide compatibility with different JavaScript projects | Primarily designed for projects using Vite
Testing libraries | Works directly with various testing libraries like React Testing Library | Requires manual integration with specific testing libraries
