### ISSUE TITLE
Separate the CM app from the Public Page

### ISSUE THREAD

**Issue by sbhamani** [PublicDataWorks/complaint-manager#378]
# Context
The Public Data page is currently tied to Complaint Manager although it has nothing to do with this app. It's a hawaii-only product and should be standalone. We would need to do the following:

1. Create a new GitHub repo (i.e. hawaii-public-data)
2. Spin up a new app with the necessary tech stack (i.e. create-react-app but something else)
3. Create a new Heroku app
4. Add this new app to Okta as a second app to CM
5. Move the DNS settings for the new hcsoc-data URL into the new Heroku app and have Hawaii update their DNS settings too
6. Add the project to the pipeline with necessary stages

# Timebox
2 Days - focus on figuring out any roadblocks and what tools/steps are needed to accomplish the above. Separate stories will be made for actually executing the work

# Notes
This would mean that the Complaint Manager would go back to having an ugly URL so we can talk to Hawaii about potentially either creating a new subdomain for it or being fine with it since it's an internal tool.

Main focus is figuring out costs associated with launching a new app.

**Comment by mariliasoaresTW** [comment]
@shaktech786 Add what is needed in terms of separating authentication?

**Comment by sbhamani** [comment]
> @sbhamani Add what is needed in terms of separating authentication?

We just would have to add another app in Okta. We should be able to continue using the same accounts for both non prod and prod.

**Comment by justin-c-anthony** [comment]
### Findings from Jean/Justin

There are a couple options for hosting the public data page on heroku:

#### 1:  Choose an eco/basic app with basic dynos: $7 a month

- low cost dynos to test ideas or run apps that see intermittent use
- deploy with git and docker
- custom domains
- container orchestration
- automatic OS-patching
- free SSL
- Automated certificate management
- never sleeps

#### 2:  Choose a production app with standard 1x dynos: $25 a month

- business focused apps, such as customer facing or internal web apps and APIs
- includes all the above features in option 1
- simple horizontal scalability
- App metrics and threshold alerts
- preboot and zero downtime deploys
- unlimited background workers

**Comment by justin-c-anthony** [comment]
https://www.heroku.com/pricing#containers
