### ISSUE TITLE
Show selected priority level and priority reasons in Case Details page

### ISSUE THREAD

**Issue by mariliasoaresTW** [PublicDataWorks/complaint-manager#380]
**Business Content**

Once we do #344 , we need to add the changes on the case details page with the new fields for Priority Level and Priority Reasons.

**In Scope**

1. Add two extra fields on the case details page to display and edit the case priority level and the priority reason.
2. Enable editing these fields and select different values from a drop down from the incident details page.

Mockups: https://www.figma.com/file/3XcaCKS0xC3U0mo98B8eTV/Features-Complaint-Manager?type=design&node-id=295-3567&mode=design&t=GYgBKqCatMgWqH2m-4

**Acceptance Criteria**

**Scenario 1: Priority level and priority reason were added on the new case dialog**
When I add a priority level and reason while creating a new case
Then I see the values populated on the incident details page

**Scenario 2: Priority level and priority reasons were not added on the new case dialog**
When I do not add values for priority level and reason while creating a new case
Then I see N/A as values on these fields

**Scenario 3: Priority level and priority reasons were not added on the new case dialog and I want to ADD those values after case is created**
When I do not add values for priority level and reason while creating a new case
Then I see N/A as values on these fields
AND I can add a priority reason and a priority type by clicking on the existing "edit" button 

**Scenario 4: Priority level and priority reasons were added on the new case dialog AND I want to EDIT those values**
When I add a priority level and reason while creating a new case and I go to the incident details page
Then I see the values populated on the incident details page 
AND I can edit the values selected previously by clicking on the existing "edit" button

**Comment by thoughtworks-vwong** [comment]
Hawaii Staging

Scenarios 1 + 4


https://github.com/PublicDataWorks/complaint-manager/assets/134408135/8ab1f7ad-00ce-4289-8768-90c294f8adcc


Scenarios 2 + 3


https://github.com/PublicDataWorks/complaint-manager/assets/134408135/0fe2695f-eca7-43de-879a-6df41099207c

**Comment by thoughtworks-vwong** [comment]
NO Staging

Scenarios 1 + 4

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/dd58b8c2-d1f7-4524-bd71-29c470d42143

Scenarios 2 + 3

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/6d5cf291-a3d7-4eb4-9cdc-f40adcd62111
