### ISSUE TITLE
Add Feature Toggles to Admin Portal

### ISSUE THREAD

**Issue by sbhamani** [PublicDataWorks/complaint-manager#410]
### Business Context:

**As a** CM Admin
**I want** to turn certain features on/off
**So that** I have control over it instead of TW

### In Scope

1. Add UI component (pending mockup) in Admin Portal to switch features on/off
2. If it doesn't exist, add an API call in the backend to be able to toggle feature flags true/false
3. Verify `feature_toggles` table is accurate and up to date for all orgs in Prod
4. Remove anything related to feature toggles from all instance files (i.e. `features.json`)

### Out of Scope

1. Retroactively adding feature flags for all features currently not having one

### Open Questions

1. Should we fix some of the language around toggle naming so they are not read as double negatives? (i.e. "removeFeature" indicates that for `true` it WON'T appear which is backwards)
2. In addition to UI toggles, are we verifying if those toggles are also checked in the API calls?

## Acceptance Criteria

1. Scenario:
   Given I am on the Admin Portal page
   When I toggle a switch for a feature from ON to OFF or OFF to ON
   Then that feature is disabled or enabled respectively

### Checklist (should be reviewed before grooming as the BA or Pair are writing the card—NOT reviewed for the first time at grooming)

- [ ] Ensure to include all necessary mockups to this card.
- [ ] Discuss what success/failure user feedback messages would be present, if any occur (front end/back end).
- [ ] Discuss Feature Flag: Where could a development flag go to flag off incomplete work? Do we want to keep the flag long-term?
- [ ] If this card is part of a sequence of cards, discuss if this card should be blocked until the testing of previous cards in the sequence have been finished.
- [ ] Have we added edge cases as ACs that we're considered from a QA perspective
- [ ] Should the new functionalities be offered only to users with certain permissions?
- [ ] How should this functionality differ between different orgs, and if it does differ, what is the hingepoint we should use for that functionality?

**Notes:**
Great practice opportunity for TDD!

**Comment by rnair-tw** [comment]
will implement part of site redesign
