### ISSUE TITLE
Make complaint type a required field in Create Case dialog

### ISSUE THREAD

**Issue by sbhamani** [PublicDataWorks/complaint-manager#411]
**Describe the bug**
In the Create Case dialog, complaint type should be a required field but it isn't. This causes the letter generation to fail if it's left empty.

**To Reproduce**
1. Go to main Cases page
2. Click on Create Case
3. Observe that the asterisk isn't there for complaint type
4. Leave it blank and finish the form
5. You will have a successful case creation instead of getting an error about the empty complaint type

**Expected behavior**
The field should be required meaning it needs to have the '*' (should occur automatically once the field is marked required) and there should be a validation message for it underneath when users try to submit an empty one.
![Image](https://github.com/PublicDataWorks/complaint-manager/assets/34656317/c94540bb-1352-4835-bbf5-59d4bdf34695)
![Image](https://github.com/PublicDataWorks/complaint-manager/assets/91492037/5288542e-e588-427b-a8cc-b14f95339745)

**Tech notes**
- This should be for both orgs

- [x] Look into CreateCaseDialog.js 
- [x] See how Intake Source dropdown implemented required field - > valida using -> [intakeSourceIsRequired] from FromFieldLevelValidation.js. 

Working Result On CI 

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/136751291/e0916362-ff6a-408a-8353-1dbe7bd0197e)

**Comment by thoughtworks-vwong** [comment]
Hawaii Staging

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/39d7d2db-e3af-4884-8bcf-cf58e85ecf35
