### ISSUE TITLE
Add Person Types to Admin Portal

### ISSUE THREAD

**Issue by sbhamani** [PublicDataWorks/complaint-manager#413]
### Business Context:

**As a** CM Admin
**I want** to update the list of Person Types I can use in cases
**So that** I have control over it instead of TW

### In Scope

1. Add UI component (pending mockup) in Admin Portal to update Person Types
2. If it doesn't exist, add an API call in the backend to be able to create, update, read, delete them (CRUD)
3. Verify `person_types` table is accurate and up to date for all orgs in Prod
4. Remove anything related to Person Types from all instance files

## Acceptance Criteria

1. Scenario:
   Given I am on the Admin Portal page
   When I click on the Person Types dropdown
   Then I'm able to add/remove/update Person Types in this view

### Checklist (should be reviewed before grooming as the BA or Pair are writing the card—NOT reviewed for the first time at grooming)

- [ ] Ensure to include all necessary mockups to this card.
- [ ] Discuss what success/failure user feedback messages would be present, if any occur (front end/back end).
- [ ] Discuss Feature Flag: Where could a development flag go to flag off incomplete work? Do we want to keep the flag long-term?
- [ ] If this card is part of a sequence of cards, discuss if this card should be blocked until the testing of previous cards in the sequence have been finished.
- [ ] Have we added edge cases as ACs that we're considered from a QA perspective
- [ ] Should the new functionalities be offered only to users with certain permissions?
- [ ] How should this functionality differ between different orgs, and if it does differ, what is the hingepoint we should use for that functionality?

**Notes:**
Great practice opportunity for TDD!

**Comment by rnair-tw** [comment]
will implement part of site redesign
