### ISSUE TITLE
Unnecessary double spacing on complaint referral letter

### ISSUE THREAD

**Issue by mariliasoaresTW** [PublicDataWorks/complaint-manager#420]
**Describe the bug**
Christian (NOIPM), has provided screenshots in the complaint referral letter where they are seeing double spacing (red squares). This example uses an unknown officer, but they are seeing the double spacing in between all officer info as well (Name, Rank, Supervisor, etc.) under the "Subject NOPD Employee Info" section. 

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/91492037/f2e1cb88-a992-48b9-9a7d-20089c93eeb1)

They have also provided the admin template as they see it. As discussed, this issue first came about when they edited text in the admin template (nothing related to spacing though).

**Steps to reproduce**
- Edit the text of the referral letter in the admin template (`/admin-portal`) (nothing related to spacing)
- Generate complaint referral letter by following these steps:
- Create a case and mark it as active
- Hit the Begin letter button
- Hit Next
- Hit Edit Letter - there are now extra new lines.

**Expected behavior**
There should not be any additional spaces in the letter. Everything in the red squares (in the screenshot) should not be there.

**Tech notes**
- Ping Shak when moving to prod as not everyone has access

**Findings**
 - When you add accused and after begin the letter and edit it before saving it, letter has no extra white space
 - When you add case note and after begin the letter and edit it before saving it , it does created extra white space 
 - When you go to admin portal and edit refferral letter and save it, go back to main page and create a case then add acussed and start a letter with the same flow as above it does add extra white space 

**Aproach**
 Update Instance files with tilda
Update Snap in instance files for referral letter - try `-u` flag for server side tests 
Push to CI, if build is successful code review/descheck/QA
Ask Shak to join for prod data update + Mariah

**Comment by mariliasoaresTW** [comment]
[oipmdoublespacingandadmintemplatescreenshots.zip](https://github.com/PublicDataWorks/complaint-manager/files/13718575/oipmdoublespacingandadmintemplatescreenshots.zip)

**Comment by rnair-tw** [comment]
![Image](https://github.com/PublicDataWorks/complaint-manager/assets/91492037/e823715d-109a-423f-860f-2a1c868e5a52)

**Comment by rnair-tw** [comment]
![Image](https://github.com/PublicDataWorks/complaint-manager/assets/91492037/fbd07198-437b-48dd-bcb0-f2f197d04f56)

**Comment by mariahsager-tw** [comment]
<img width="879" alt="Screenshot 2024-01-31 at 10 45 10 AM" src="https://github.com/PublicDataWorks/complaint-manager/assets/107599128/2a69e28b-97cc-408c-b962-29772e97cb5a">
<img width="921" alt="Screenshot 2024-01-31 at 10 46 06 AM" src="https://github.com/PublicDataWorks/complaint-manager/assets/107599128/6e81d3aa-218a-40a3-b73e-31049594f909">

**Comment by mariahsager-tw** [comment]
- We have determined that the issue is with Handlebars.js adding extra new lines
- Relevant StackOverflow: https://stackoverflow.com/questions/21713227/how-to-remove-newlines-generated-by-handlebars
- Adding `~`s in the correct locations fixes the issue
- We just now have to figure out where to make the fix.

**Comment by mariahsager-tw** [comment]
- `instance_files_noipm` [commit](https://github.com/PublicDataWorks/instance_files_noipm/commit/aa1b96c4b039210d705eb2a8016c58f27bf6a992?diff=split&w=0)
- `instance_files_hawaii_csoc` [commit](https://github.com/PublicDataWorks/instance_files_hawaii_csoc/commit/51ed5cdb4dd8339a2051849598c2603dbfe6d0ac)

**Comment by rnair-tw** [comment]
https://app.circleci.com/pipelines/github/PublicDataWorks/complaint-manager/2520/workflows/38f2f25a-b0c0-4231-ad20-3dbc7d75a926/jobs/19790

**Comment by heliofreitastw** [comment]
Link for the wiki: https://sites.google.com/thoughtworks.com/tw-invisible-institute-wiki/development-resources/how-to-guides/how-to-update-the-pdf-snapshot

**Comment by thoughtworks-vwong** [comment]
Verified double spacing no longer appears on complaint referral letter.

Hawaii

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/52f83e66-4ac8-408d-885c-a842badd46e8

NO

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/ede4fc6b-646c-448c-ae38-220e10f9853e

**Comment by thoughtworks-vwong** [comment]
Verified double spacing shown above no longer appears on complaint referral letter.

NOIPM

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/3141c33d-fcb6-4e57-af7a-08cfc832c36b

**Comment by rnair-tw** [comment]
Received confirmation from Christian that it works.

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/91492037/c7f42a26-d1a4-4d86-b349-86e8b6778cc9)
