### ISSUE TITLE
Supervisor names not showing up for certain officers in Case Details page

### ISSUE THREAD

**Issue by mariliasoaresTW** [PublicDataWorks/complaint-manager#424]
Dependency: updating officers data - to be done on #328 

**Bug:** supervisor is not showing for some officers like “Alijah OConnor (Id = 16886)

**Steps to Reproduce:**
1. In the case details view look at the supervisor data and check where the code is pointing to. It should be the officer_number info (first name, last name and officer_number) 

2. It *seems* like the code is actually pulling the windows_username or other fields when trying to find the supervisor data for an officer.

**Learnings:** We learned that in this case Alijah's supervisor is Nikia Adams, officer_number 14120. For some reason we are not displaying that info on the supervisor field

**Comment by rnair-tw** [comment]
duplicate, combined w/ #329
