### ISSUE TITLE
Do an audit of reminders in slack (change, as needed)

### ISSUE THREAD

**Issue by rnair-tw** [PublicDataWorks/complaint-manager#426]

**Comment by faraakhatTW** [comment]
There is reminder  `/remind` key you can use in order to set new reminder and also chose which chanel and what time it to be set with a context you need to add. 

Note: whoever sets a new reminder is only can delete reminder message as a single owner.

**Comment by faraakhatTW** [comment]
Current slackbot responses are 10. Most of them already deactivated by Andrew. Please take a look and review and let me know if we want to delete some of them or reinstate ? 


![Image](https://github.com/PublicDataWorks/complaint-manager/assets/136751291/aa0fa55c-f2bb-4ee4-bb9f-2ede3fd6b440)



![Image](https://github.com/PublicDataWorks/complaint-manager/assets/136751291/4934dbf6-9f04-403b-8dfb-486be73c1880)



![Image](https://github.com/PublicDataWorks/complaint-manager/assets/136751291/2bc6f69f-351f-42d6-b38e-d894d0a854f7)



![Image](https://github.com/PublicDataWorks/complaint-manager/assets/136751291/36dc4fca-466c-42ca-82e9-b3fa3ebcdf61)



![Image](https://github.com/PublicDataWorks/complaint-manager/assets/136751291/a49cc4b0-c52e-4f8f-a85b-f29c348c0324)



![Image](https://github.com/PublicDataWorks/complaint-manager/assets/136751291/89d0d347-87ac-4589-821c-939719d3f37b)



![Image](https://github.com/PublicDataWorks/complaint-manager/assets/136751291/0c849ee7-94fe-462f-8356-7152c0b86be7)



![Image](https://github.com/PublicDataWorks/complaint-manager/assets/136751291/5e6b611e-9ec1-44a5-8274-0060e3da26f0)



![Image](https://github.com/PublicDataWorks/complaint-manager/assets/136751291/e6e87705-4aa7-4623-97af-9cd905842f14)



![Image](https://github.com/PublicDataWorks/complaint-manager/assets/136751291/f251a613-74b4-40fa-8a00-11c673c12305)

**Comment by rnair-tw** [comment]
for `core team channel` please remove the following (will set a new one up myself):
![Image](https://github.com/PublicDataWorks/complaint-manager/assets/91492037/c9951ed4-8c79-4344-b04d-b73bc555acfc)
