### ISSUE TITLE
Import new officers to the officers table in PROD

### ISSUE THREAD

**Issue by heliofreitastw** [PublicDataWorks/complaint-manager#458]
### Business Context:
Use the information in the attached officer CSV below to perform an update on the officer table in prod.

### Additional context
Some time ago last year, there was an issue with the officers table where the data had a lot of duplication. In order to create a new case, there needed to be a lot of workarounds in order to find the correct officer. This card ensures that the correct data is uploaded to the table. 

### In Scope
* Make a backup of the officers table before importing the CSV
SKIP THIS STEP * Set the start date of the search officers functionality
SKIP THIS STEP  * Start date should be 1 day before we are doing the upload
SKIP THIS STEP  * environment variable name PRODUCTION_OFFICER_ROSTER_LATEST_DATE
SKIP THIS STEP   * The time is in epoch format (seconds) https://www.epochconverter.com/
* Update officers table in production for NOIPM with the attached CSV
* Test it works (log into prod or meet w/ Christian)

Link for file: https://github.com/PublicDataWorks/complaint-manager/files/13746563/Officers.CSV.-.Sheet1.csv

### Notes
- [x] make copy of CSV from NO Prod 
- [x] Set Date to 1/30/2024 in epoch time 
- [ ] Update officers table in production for NOIPM with the attached CSV
- [ ] Make sure append new officers into existing table with old info

### Checklist
Kickoff
- [x] We have we indicated which organizations and user permissions require this
- [x] We have indicated whether we have any dependancies to other cards/work
- [x] We have indicated which environment this can be tested in
- [x] We have included a mockup if this is design related
- [x] We have included clear ACs to test it
- [x] We have estimated the story

Deskcheck
- [ ] This work has been demoed in staging (or higher) and led by the dev pair who worked on this card
- [ ] We have run through and passed all the ACs
- [ ] Our documentation has been updated
- [ ] Our onboarding checklist has been updated

**Comment by rnair-tw** [comment]
![Image](https://github.com/PublicDataWorks/complaint-manager/assets/91492037/b41c18a2-9d69-4828-abe6-91d8fbc29953)

**Comment by claireholt-tw** [comment]
1. Download the officers table from prod and import it into local
2. Figure out the Update SQL command
3. Create a new table with the new_officer_roster.csv
4. Update officers using new_officer_roster (?)
5. Drop new_officer_roster
6. Run it
7. Fix errors
8. Do it in prod!

**Comment by claireholt-tw** [comment]
Update: Upon further investigation, I saw NOIPM included a new value for employee_type, "Civilian". In the past, employee_type was an enum that only accepted the values "Commissioned", "Non-Commissioned", or "Recruit". 

I'll need to write a migration to allow employee type to accept the value "Civilian". I'll write this migration to update employee_type in both the officers tables and cases_officers table.

**Comment by claireholt-tw** [comment]
In order to update the prod database with the new roster, we need to drop the uniqueOfficerNumber constraint from the officers table.

We've got to do this because in our new roster windows username was just copied and pasted into the officer number field, and coincidentally some people's windows usernames is the same as other people's officer number, thus violating the constraint.

We're going to delete the constraint, which shouldn't be a big deal because we're dropping the entire officer number column in future cards.
