### ISSUE TITLE
Make priority level and priority reason a required field in Create Case dialog

### ISSUE THREAD

**Issue by faraakhatTW** [PublicDataWorks/complaint-manager#459]
Depends on this [Card](https://github.com/orgs/PublicDataWorks/projects/1/views/3?pane=issue&itemId=36560684)

**Comment by faraakhatTW** [comment]
Input fields now has required warning in CI-Hawaii 

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/136751291/c0b618f6-bed1-42a8-a2f3-1961193602f4)

**Comment by thoughtworks-vwong** [comment]
Hawaii Staging

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/efea1213-d8fd-4b99-bdf1-c47572da902d

**Comment by thoughtworks-vwong** [comment]
NO Staging

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/6abc45bd-4628-48c5-86f5-fdfd7eb8c5c5
