### ISSUE TITLE
Hide fields that do not apply based on user selection in Case Details page

### ISSUE THREAD

**Issue by rnair-tw** [PublicDataWorks/complaint-manager#464]
### User Story
As an intake specialist
I only want to see fields that are used in my organization
So that I do not get confused by redundant fields and can quickly find the information I need 

### Business Context:
Currently, when the user selects `Priority Incident` as the `Intake Source` and selects a value for both the `Priority Level` and `Priority Reason`, once they edit this and select something other than `Priority Incident` as the `Intake Source`, the original `Priority Level` and `Priority Reason` still persist in the Case Details page. The expected behavior should be that the `Priority Level` and `Priority Reason` are N/A.  

This is an example of the incorrect behavior:
![Image](https://github.com/PublicDataWorks/complaint-manager/assets/91492037/a4d36e98-2723-4feb-be69-309ca52b75f8)

Therefore, to minimize confusion, we want to ensure if if `Priority Reason` is not selected as the `Intake Source`, we do not show the `Priority Level` and `Priority Reason` fields.  

Ping Karhan when working on this for the UI.

### In Scope
1. On the Intake Source field add new logic
2. `Priority Reason` is not selected as the `Intake Source`, we do not show the `Priority Level` and `Priority Reason` fields in the Case Details page
3. And the values for `Priority Level` and `Priority Reason` will be NULL in the db

### Out of Scope
1. 

### Open Questions
1. What happens to the data in the backend?

## Acceptance Criteria

1. Scenario: 
Given I have selected `Priority Incident` as the `Intake Source` and chosen a value for both the `Priority Level` and `Priority Reason`
When I change the `Intake Source` to something other than `Priority Incident` as the `Intake Source`
Then the `Priority Level` and `Priority Reason` are not shown in the Case Details page

2. Scenario: 
Given 
When
Then 

### Checklist
Kickoff
- [x] We have we indicated which organizations and user permissions require this
- [x] We have indicated whether we have any dependancies to other cards/work
- [x] We have indicated which environment this can be tested in
- [x] We have included a mockup if this is design related
- [x] We have included clear ACs to test it
- [x] We have estimated the story

Deskcheck
- [x] This work has been demoed in CI (or higher) and led by the dev pair who worked on this card
- [x] We have run through and passed all the ACs
- [x] Our documentation has been updated
- [x] Our onboarding checklist has been updated

**Comment by heliofreitastw** [comment]
Outcome of the kickoff for the layout of the page: remove the fields and leave the others as is

**Comment by thoughtworks-vwong** [comment]
Verified fields that do not apply based on user selection in case details page are hidden.

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/0152d7b9-dcce-47c8-8ea2-78d5be8f60c2
