### ISSUE TITLE
Change the prompt when deleting a letter type

### ISSUE THREAD

**Issue by rnair-tw** [PublicDataWorks/complaint-manager#466]
### User Story
As a system administrator 
I want to see a message when I try to delete a letter type
So that I am clear about the implication of deleting to current and future letters and can proceed knowing this

### Business Context:
Existing behavior, when the user tries to delete a letter type, they will get the following error:
![Image](https://github.com/PublicDataWorks/complaint-manager/assets/91492037/b18169fc-d94e-441e-b85e-c094372cd461)

We would like to change the message to the text in the mockup.

### In Scope
1. In the Admin Portal
2. Change the existing message
3. Add a X button and a test for this
4. No and Cancel have the same behavior

### Out of Scope
1. Changing the styling of the button, please keep what is the current styling

### Mockups

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/91492037/b5307eee-9214-4045-90a2-29f5fc2216ed)

## Acceptance Criteria

1. Scenario: 
Given I have created a new letter type
And there is an existing letter generated using it
OR there is no existing letter generated using it
When I try to delete the letter type
Then I see the specified error message (refer to business context)

2. Scenario: 
Given 
When
Then 

### Checklist
Kickoff
- [ ] We have we indicated which organizations and user permissions require this
- [ ] We have indicated whether we have any dependancies to other cards/work
- [ ] We have indicated which environment this can be tested in
- [ ] We have included a mockup if this is design related
- [ ] We have included clear ACs to test it
- [ ] We have estimated the story

Deskcheck
- [ ] This work has been demoed in CI (or higher) and led by the dev pair who worked on this card
- [ ] We have run through and passed all the ACs
- [ ] Our documentation has been updated
- [ ] Our onboarding checklist has been updated

**Comment by rnair-tw** [comment]
Normal priority - to add more details to this

**Comment by rnair-tw** [comment]
@kjonesthoughtworks

**Comment by claireholt-tw** [comment]
Note from deskcheck - Not all instances of ConfirmationDialogs have the same styling, some have custom styling applied

**Comment by thoughtworks-vwong** [comment]
Verified prompt is changed when deleting a letter type.

Hawaii

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/7f940f24-dd96-4955-b825-258832285e96

NO

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/87739f54-f2da-488f-a3b3-1de0c0e496b5
