### ISSUE TITLE
Remove fields not relevant to the organization in Incident Details

### ISSUE THREAD

**Issue by rnair-tw** [PublicDataWorks/complaint-manager#467]
### User Story
**As a** user in Hawaii
**I want to** see fields relevant to my organization
**So that** I am not confused by field I don't use and can quickly find the information I need

### Business Context:
In the Incident Details, there are a lot of fields that organizations do not use. We therefore want to remove unused fields for a better user experience. We also want to ensure users won't see the removed fields when they create a new case or edit the case. Do not show the following fields in Incident Details and Edit Incident Details for Hawaii:
- PGB Case Number
- How did you hear about us?

### In Scope
1. Remove PGB Case Number
2. Remove How did you hear about us?
3.

### Out of Scope
1. 

### Mockups
Refer to this: https://www.figma.com/file/3XcaCKS0xC3U0mo98B8eTV/Features-Complaint-Manager?type=design&node-id=588-5253&mode=design

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/165818433/030027d3-a2c4-416b-8261-e19fd64fb345)

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/165818433/40590a73-1617-4102-a489-dc82ad2c23f3)

## Acceptance Criteria

1. Scenario: 
**Given** I am in the Case Details page
**When** I look at the Incident Details section
**Then** I do not see the fields that are irrelevant for my organization (refer to business context)

### Checklist
Kickoff
- [x] We have we indicated which organizations and user permissions require this
- [x] We have indicated whether we have any dependancies to other cards/work
- [x] We have indicated which environment this can be tested in
- [x] We have included a mockup if this is design related
- [x] We have included clear ACs to test it
- [x] We have estimated the story

Deskcheck
- [x] This work has been demoed in staging (or higher) and led by the dev pair who worked on this card
- [x] We have run through and passed all the ACs
- [x] Our documentation has been updated
- [x] Our onboarding checklist has been updated

**Comment by rnair-tw** [comment]
@kjonesthoughtworks to add mockup

**Comment by rnair-tw** [comment]
@rowsnr to create mockup for checkbox for priority incident and we need to show it to christin for feedback

**Comment by rowsnr** [comment]
> [@rowsnr](https://github.com/rowsnr) to create mockup for checkbox for priority incident and we need to show it to christin for feedback

https://www.figma.com/file/3XcaCKS0xC3U0mo98B8eTV/Features-Complaint-Manager?type=design&node-id=588-5253&mode=design

**Comment by thoughtworks-vwong** [comment]
Verified irrelevant fields were removed in incident details.

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/d85f886f-1495-4a82-807b-a41a1affb23b
