### ISSUE TITLE
Image broken on Hawaii Public Data Dashboard (live site)

### ISSUE THREAD

**Issue by kjonesthoughtworks** [PublicDataWorks/complaint-manager#485]
**Describe the bug**
There's an image missing at the bottom of the HSOC Public Data page: https://hcsoc-data.hawaii.gov/public-data

This should be the image: https://hcsoc-data.hawaii.gov/images/MenPrison_StockImg.jpeg

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/91492037/10e60446-3bd7-4c8d-8d1f-1c4339ed0ab5)

**Steps to reproduce**
List any steps to reproduce behavior 
1. Open the HSOC Public Data page
2. Scroll to the bottom and see missing image

**Expected behavior**
The image should load as expected.

**Checklist**
- [x] Indicate bug severity on the right

**Comment by thoughtworks-vwong** [comment]
Verified image is no longer broken on staging (https://noipm-staging.herokuapp.com/public-data)

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/134408135/8caf041b-a676-4054-a36b-554b67fb8c06)
