### ISSUE TITLE
Organize meeting to discuss ways to improve backend for v2.0

### ISSUE THREAD

**Issue by faraakhatTW** [PublicDataWorks/complaint-manager#490]
Organize meeting in team calendar for Dev/QA to discuss ways to improve backend for `Complaint Manager 2.0`
This meeting conversation will be around how improve and optimize backend for `Complaint Manager 2.0` MVP for now. 

@sbhamani and @heliofreitastw will be discussing current paint point in the backend 1.0

**Comment by claireholt-tw** [comment]
Dev pain point sheet: https://docs.google.com/spreadsheets/d/1-bwL4KspGGeGNwESp7CvbwP8AOjrAhbldksP9dJLihw/edit#gid=1185070149
