### ISSUE TITLE
Migrate Wiki from Google

### ISSUE THREAD

**Issue by rnair-tw** [PublicDataWorks/complaint-manager#499]
Context: We want to migrate our existing wiki in Google to another platform as we want more structure and transparency for our product, as we want it eventually become a Digital Public Good.

Digital Public Good requirement:
> The digital solution must have documentation of the source code, use cases, and/or functional requirements. For content, this should include all relevant/compatible apps, software, or hardware required to access the content, and instructions regarding how to use it. For software digital solutions, this should be technical documentation that would allow a technical person unfamiliar with the digital solution to launch and run the software.

Google wiki: https://sites.google.com/thoughtworks.com/tw-invisible-institute-wiki/project-overview?authuser=0
Github pages: https://publicdataworks.github.io/complaint-manager/
GitHub wiki: https://github.com/PublicDataWorks/complaint-manager/wiki

Tasks:
- [x] Figure out if GitHub is the best place or there is a better place to store our documentation (refer to other best practices)
  - [x] Create ADM ([link](https://docs.google.com/spreadsheets/d/1CnENYvGxAxI-C9YUOJot7cYBVaAnOW06jlZBjD66tOQ/edit#gid=0))
  - [x] Present ADM (03/05/24)
  - [x] Create ADR ([link](https://github.com/PublicDataWorks/complaint-manager/wiki/ADRs#002---hosting-our-wiki-somewhere-other-than-google-sites))
- [x] Do an audit of current Google wiki, what should be moved vs stay? Come up with general guidelines and sensible defaults - Try to finish by end of March, plan is to have listed out and then schedule 2 meetings
- [x] Define structure for new wiki and present this to the team - mid April
- [ ] Set up whatever wiki we decide to move to
- [ ] Do the migration - end of April

- [ ] Move the wiki to the new repo, [iw-complaint-manager](https://github.com/Impactworkers/iw-complaint-manager)

https://team-ai-owd2wjctzq-uc.a.run.app/teamai/

**Comment by rnair-tw** [comment]
Some places used for documentation:
- Confluence (e.g. https://bahmni.atlassian.net/wiki/spaces/BAH/overview?homepageId=491527)
- Readthedocs (e.g. https://uwazi.readthedocs.io/en/latest/index.html uses https://about.readthedocs.com/?ref=readthedocs.org)
- PDF docs (e.g https://github.com/GRS-DPG/GRS-Documentations/tree/master/PDF)
- Their own website? (e.g. https://aam-digital.github.io/ndb-core/documentation/additional-documentation/overview.html)

**Comment by mariahsager-tw** [comment]
ADM [here](https://docs.google.com/spreadsheets/d/1CnENYvGxAxI-C9YUOJot7cYBVaAnOW06jlZBjD66tOQ/edit#gid=0)

**Comment by mariahsager-tw** [comment]
ADR [here](https://github.com/PublicDataWorks/complaint-manager/wiki/ADRs#002---hosting-our-wiki-somewhere-other-than-google-sites)

**Comment by rnair-tw** [comment]
Audit here: https://docs.google.com/spreadsheets/d/1lUTczYwrRtepxKhdMQAI4-3z7HXNVb-rkXrZO-m4zvI/edit?pli=1#gid=0
