### ISSUE TITLE
Evaluate if we should use Tailwind CSS or SASS with MUI for v2.0

### ISSUE THREAD

**Issue by rnair-tw** [PublicDataWorks/complaint-manager#502]
Context: A CSS framework would offer additional benefits in terms of customization, consistency and development efficiency vs styling MUI directly. We therefore have narrowed down to two frameworks, Tailwind CSS and SASS (Syntactically Awesome Style Sheets) that seem suitable for our purposes. We therefore want to figure out which suits our project needs the best based on requirements, flexibility, maintainability, team experience, etc.

Tailwind CSS: Provides utility classes for styling directly in HTML
SASS: Enhances CSS with features like variables and mix ins to facilitate more structured and maintainable stylesheets

**Comment by sbhamani** [comment]
Going to go with SASS as it is a more usable framework to learn for future projects and provides good CSS organization, whereas Tailwind is less scalable, and we can always switch to it in the future whereas SASS needs a good foundational setup.
