### ISSUE TITLE
Verify costs to maintain system infrastructure

### ISSUE THREAD

**Issue by rnair-tw** [PublicDataWorks/complaint-manager#503]
Context: We would like to ensure that our clients are aware of the costs to maintain the system for their knowledge as well as planning, if they eventually will need to host their own system. We currently have a page that list this out (last updated: 03/01/2021), but this need to be updated based on our current costs. 

Existing doc: https://publicdataworks.github.io/complaint-manager/technical-content/new-city-setup/infrastructure-setup.html

**Comment by sbhamani** [comment]
Collating results here: https://docs.google.com/spreadsheets/d/1d2hS2-CUhddDFfZn2CWvLYbqT-GUxl7FXDe4QJmee8o/edit#gid=0
