### ISSUE TITLE
Investigate third party cookie restrictions for Chrome

### ISSUE THREAD

**Issue by sbhamani** [PublicDataWorks/complaint-manager#505]
### Business Context
Investigate this Chrome change: Prepare for third-party cookie restrictions (https://developers.google.com/privacy-sandbox/3pcd#report-issues) and see how it would affect our current system.

### Timebox
1 day

### Notes
Add comments from investigation in card, if ADR is needed let us know

**Comment by arihu1008** [comment]
We found ways to visualize the usage of the third party cookies in our app by using a Chrome extension called [Privacy Sandbox Analysis Tool](https://chromewebstore.google.com/detail/privacy-sandbox-analysis/ehbnpceebmgpanbbfckhoefhdibijkef). To test if the app breaks without the third party cookies, you can enable the Test Third Party Cookie Phaseout in Chrome flag`chrome://flags/#test-third-party-cookie-phaseout`

We didn't have any trouble using the app with the flag enabled. 
You can find more details from this [link](https://developers.google.com/privacy-sandbox/3pcd/prepare/test-for-breakage)
