### ISSUE TITLE
Determine what to use to send users email notifications when tagged

### ISSUE THREAD

**Issue by rnair-tw** [PublicDataWorks/complaint-manager#516]
### Business Context
In #508 we have a user request, where they would like to receive an email when they are tagged in a case note. Currently they only see a notification after logging into the system, which doesn't meet their needs. We therefore would like to explore what's the best and cheapest (ideally free) way to send users notifications to the email they use to log into the system. The output of this is an ADR.

ADR template: https://publicdataworks.github.io/complaint-manager/adrs/adr-template

### Timebox
2 days

### Notes
Requirements:
- Open source
- Ideally free, no branding 
- AWS might work, very cheap

Once we decide on this, we need an ADR.

**Comment by justin-c-anthony** [comment]
Link to AWS email subscriptions info: https://docs.aws.amazon.com/sns/latest/dg/sns-email-notifications.html

**Comment by justin-c-anthony** [comment]
Link to AWS SNSspike info: https://gist.github.com/justin-c-anthony/8e199258d01c9d6862328502170036ef
