### ISSUE TITLE
How to update the table in a much more seamless manner

### ISSUE THREAD

**Issue by rnair-tw** [PublicDataWorks/complaint-manager#529]
### Business Context
Keeping the officer table updated is very difficult for our team due to issues with duplication, missing data, incorrect data etc. We therefore want to spike the most effective way to keep this table updated for our users. Whatever we decide on has to work for both Hawaii and New Orleans (officer roster and inmates).

Some options:
- Get them to be in control of adding/removing folks to this table with very little effort on our end for maintenance (requires building something)
- Let us still be in control, but look at a different way of updating the table (e.g. using flatfile.com)

### Definition of Done: 
The output of this should be a ADR.

### Timebox
3 days

### Ac's: Do research/play around and answer:
- [ ] Is there possible none/tech solution? Name and Link -> 
- [ ] What are the advantages and disadvantages ? 
- [ ] Is the value add is worth it? 
- [ ] How difficult is implementation ?
- [ ] Record your findings in form of documentation(markdown or ADR)
- [ ] Present/Deskcheck your findings. (Meeting should include TL,PM,BA,UX,QA)
- [ ]  If approved write down the steps in a new Story Card

### Notes
xxxx

**Comment by rnair-tw** [comment]
maybe use flatfile: https://flatfile.com/

**Comment by heliofreitastw** [comment]
Add comment to the card with the outcome. In the desk check it will be decided if the proposal will become an ADR.

**Comment by paul-thompson1** [comment]
# The below information is in regards to Python scripts and SQL Queries. Some alternatives to Python scripts include **shell scripts** and **node scripts**.


### **Pandas (Python)**

Python's Pandas library is well-suited for data manipulation and analysis tasks, including automation of PostgreSQL database-related tasks. Here are some example use cases where a Python script using Pandas can automate PostgreSQL database tasks:

1. **Data Import and Export**:
   - **Use Case**: You want to import data from a CSV file into a PostgreSQL table and export query results to a CSV file.
   - **Script**: The script can use Pandas to read data from a CSV file into a DataFrame, then use `to_sql()` to write the DataFrame to a PostgreSQL table. Similarly, it can use SQL queries to fetch data from PostgreSQL into a DataFrame and then use Pandas to export the DataFrame to a CSV file.

2. **Data Cleaning and Transformation**:
   - **Use Case**: You need to clean and transform data stored in a PostgreSQL database before further analysis.
   - **Script**: The script can use SQL queries to fetch data into a DataFrame, then use Pandas functions to clean and transform the data, such as handling missing values, converting data types, or applying custom transformations. Finally, it can write the cleaned and transformed data back to the database.

3. **Automated Reporting**:
   - **Use Case**: You want to automate the generation of reports or dashboards based on data stored in a PostgreSQL database.
   - **Script**: The script can use SQL queries to fetch relevant data into a DataFrame, then use Pandas and visualization libraries like Matplotlib or Seaborn to generate reports or dashboards. You can schedule the script to run periodically using tools like cron or Task Scheduler to ensure regular updates.

4. **Data Aggregation and Analysis**:
   - **Use Case**: You need to perform complex data aggregation and analysis tasks on data stored in PostgreSQL.
   - **Script**: The script can use SQL queries to fetch data into a DataFrame, then use Pandas to perform various aggregation and analysis tasks, such as calculating summary statistics, grouping data, or applying machine learning models. The results can be stored back in the database or used for further analysis.

5. **Schema Migration and Management**:
   - **Use Case**: You want to automate schema migration tasks, such as adding new columns, modifying column data types, or dropping tables.
   - **Script**: The script can use SQL queries to execute schema migration operations on the PostgreSQL database, then use Pandas to validate the changes or perform additional data migration tasks if needed.

These are just a few examples of how a Python script using Pandas can automate PostgreSQL database-related tasks. Depending on your specific requirements and use cases, you can customize and extend these scripts to suit your needs.

### PostgreSQL SQL Queries

PostgreSQL, being a powerful relational database management system (RDBMS), supports a wide range of SQL queries. Here's an overview of some common SQL queries available in PostgreSQL:

1. **SELECT**: Used to retrieve data from one or more tables based on specified criteria. SELECT queries can include filtering conditions, sorting, grouping, and joining multiple tables.

   Example:
   ```sql
   SELECT column1, column2 FROM table WHERE condition;
   ```

2. **INSERT**: Used to add new records (rows) to a table.

   Example:
   ```sql
   INSERT INTO table (column1, column2) VALUES (value1, value2);
   ```

3. **UPDATE**: Used to modify existing records in a table.

   Example:
   ```sql
   UPDATE table SET column1 = value1 WHERE condition;
   ```

4. **DELETE**: Used to remove records from a table based on specified criteria.

   Example:
   ```sql
   DELETE FROM table WHERE condition;
   ```

5. **CREATE TABLE**: Used to create a new table.

   Example:
   ```sql
   CREATE TABLE table_name (
       column1 datatype,
       column2 datatype,
       ...
   );
   ```

6. **ALTER TABLE**: Used to modify an existing table (e.g., add or drop columns, change column data types).

   Example:
   ```sql
   ALTER TABLE table_name ADD column_name datatype;
   ```

7. **DROP TABLE**: Used to delete a table and its data.

   Example:
   ```sql
   DROP TABLE table_name;
   ```



8. **CREATE INDEX**: Used to create an index on a table to improve query performance.

   Example:
   ```sql
   CREATE INDEX index_name ON table_name (column_name);
   ```

9. **DROP INDEX**: Used to remove an index from a table.

   Example:
   ```sql
   DROP INDEX index_name;
   ```

10. **SELECT DISTINCT**: Used to retrieve unique values from a column.

    Example:
    ```sql
    SELECT DISTINCT column_name FROM table_name;
    ```

11. **GROUP BY**: Used to group rows that have the same values into summary rows.

    Example:
    ```sql
    SELECT column1, COUNT(*)
    FROM table_name
    GROUP BY column1;
    ```

12. **HAVING**: Used to filter groups based on aggregate conditions.

    Example:
    ```sql
    SELECT column1, COUNT(*)
    FROM table_name
    GROUP BY column1
    HAVING COUNT(*) > 1;
    ```

13. **ORDER BY**: Used to sort the result set based on one or more columns.

    Example:
    ```sql
    SELECT column1, column2
    FROM table_name
    ORDER BY column1 ASC, column2 DESC;
    ```

14. **LIMIT**: Used to limit the number of rows returned by a query.

    Example:
    ```sql
    SELECT * FROM table_name LIMIT 10;
    ```

15. **OFFSET**: Used to skip a specified number of rows before returning the result set.

    Example:
    ```sql
    SELECT * FROM table_name OFFSET 10;
    ```

16. **UNION, INTERSECT, EXCEPT**: Used to combine or compare the result sets of two or more SELECT queries.

    Example:
    ```sql
    SELECT column1 FROM table1
    UNION
    SELECT column1 FROM table2;
    ```

These are just some of the SQL queries available in PostgreSQL. PostgreSQL supports many other SQL features and functionalities for managing and querying data efficiently. Always refer to the PostgreSQL documentation for detailed information on SQL queries and their usage.

**Comment by justin-c-anthony** [comment]
## Client Side Data Management vs Development Team Data Management

### Client Side Data Management (Through CREATE/UPDATE/ARCHIVE/DELETE functionality in UI)

#### Pros
- Officers/Identities can be updated from the UI by the user instead of passing information across channels. 
- Eliminates the bottleneck of trying to reconcile large amounts of data being updated all at once that is passed from one org to another
- gives control over the data to the client
- saves valuable time for developers by allowing them to focus on delivering features and fixing bugs as opposed to the time consuming task of data entry which is error prone
- allows us to have more control over checking for duplications and making sure the required information is provided in input fields
- eliminates the inconsistencies of data being passed from one org to another by standardizing required information

#### Cons
- 

### Dev Team Data Management

#### Pros
-

#### Cons
- Very time consuming and error prone
-

**Comment by rnair-tw** [comment]
![Image](https://github.com/PublicDataWorks/complaint-manager/assets/91492037/832894a9-6a13-4632-8265-418a32d4154b)
