### ISSUE TITLE
Investigate why charts don't resize in data dashboard

### ISSUE THREAD

**Issue by rnair-tw** [PublicDataWorks/complaint-manager#535]
Investigate why the charts don't resize to fit the screen. Perhaps responsiveness not built into the design but wondering if there's a quick fix to implement this. If big effort we will not change this. 

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/91492037/5a164850-a3e7-4c44-929c-0af42987ea33)

**Comment by espinolaJ-TW** [comment]
Notes:

- The design didn't seemed to consider responsiveness
- Data components have a fixed height and width

Possible Solutions:
- A quick fix would be to add flow-flex wrappers around the visual components, but resizing for smaller screen would be limited. 
- Create css file to add stying for data components in the Data Dashboard page.
