### ISSUE TITLE
Set up new Heroku application

### ISSUE THREAD

**Issue by rnair-tw** [PublicDataWorks/complaint-manager#536]
### User Story
As a developer
I want to set up a new heroku application
So that ensure my app runs smoothly without worrying too much about complicated sever maintenance

### Definition of Done
- Heroku team `Impactworkers` exists
- Heroku app `cm-dev` exists 
- Heroku app is hooked up to `iw-complaint-manager` repo

### Acceptance Criteria
**Given** that this is set up
**When** I go to `cm-dev.herokuapp.com`
**Then** I can make sure the URL loads

**Note:** If the setup procedure allows you to create a postgres instance for `cm-dev`, then go ahead and do that here and merge #540 into this card.

**Comment by devonivory** [comment]
when creating a new team the team name must be lowercase.

**Comment by heliofreitastw** [comment]
The app was created. The access link is https://cm-dev-872d2dccc62f.herokuapp.com/

We don't have the option to modify this domain to `cm-dev.herokuapp.com`. We can add a custom domain though.
For more info view: [herokuapp.com subdomain names are changing](https://devcenter.heroku.com/changelog-items/2597)
