### ISSUE TITLE
Create onboarding Bash Script for new developers

### ISSUE THREAD

**Issue by paul-thompson1** [PublicDataWorks/complaint-manager#548]
### Context:

New developers are onboarding. I thought it would save time to have a bash script that detects what software is not installed and then installs the software.

### The script will install the following software if not already installed:

- Brew
- DBeaver
- Docker Desktop
- Git
- NVM
- PostgreSQL app
- VS Code
- Yarn

The script also detects the system architecture of the device and installs the appropriate software for that system. For example, **ARM64** will get **ARM64 software** and **AMD64** will get **AMD64 software**.

The script is intended to only be run on **MAC OS** systems at the moment.

I can make modifications to the script in the **future** or make other **scripts**. For example, I could make a script that helps with setting up an **SSH key** for GitHub. Or I could basically automate the entire **initial developer setup**.

**Comment by rnair-tw** [comment]
Question: Can we create something similar for non-dev roles?

**Comment by paul-thompson1** [comment]
> Question: Can we create something similar for non-dev roles?

I would need more context on what non-dev roles require before I can give a definite answer. If the software can be installed locally and the software is available from an online source then I can make a script to automate the installation process.
