### ISSUE TITLE
Change commissioner name in letterhead

### ISSUE THREAD

**Issue by rnair-tw** [PublicDataWorks/complaint-manager#550]
### User Story
As a user from Hawaii
I want to ensure that the letterhead Commissioner is changed
So that the letterhead reflects the current leadership

### Business Context:
We need to update the Hawaii letterhead as Commissioners have changed. Note that there will be another change coming in June, so good to explore a way to make this easier.

It should look like this:
![Image](https://github.com/PublicDataWorks/complaint-manager/assets/91492037/b055a35a-ec1c-49d4-87dd-e87088eaeb5f)

### In Scope
1. Refer to the new image in the comments
2. Update the letterhead with latest image

### Acceptance Criteria

1. Scenario: 
Given I am in Hawaii
And I generate a new letter with the updated template
When I look at the top right of the letter
Then I see the new Commissioner names

2. Scenario: 
Given 
When
Then 

### Checklist
Kickoff
- [x] We have we indicated which organizations and user permissions require this 
- [x] We have indicated whether we have any dependencies to other cards/work
- [x] We have indicated which environment this can be tested in
- [x] We have included a mockup if this is design related
- [x] We have included clear ACs to test it
- [x] We have estimated the story

Deskcheck
- [x] This work has been demoed in CI (or higher) and led by the dev pair who worked on this card
- [x] We have run through and passed all the ACs
- [x] Our documentation has been updated
- [x] Our onboarding checklist has been updated

**Comment by justin-c-anthony** [comment]
NOTE

Current Image Pixel size is: 2151 × 580 pixels

**Comment by justin-c-anthony** [comment]
new image pixel size: 1768 × 602 pixels

**Comment by justin-c-anthony** [comment]
Original Image:

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/148882957/4c904caa-714e-4645-b439-f7669b20e194)

**Comment by rnair-tw** [comment]
@rowsnr to work on vectorizing the image to make it easier to do future updates

**Comment by rowsnr** [comment]
![white-bg-hcsoc-letterhead](https://github.com/PublicDataWorks/complaint-manager/assets/165818433/a1825878-4d00-40a2-a29c-78316c418646)

**Comment by rowsnr** [comment]
![Image](https://github.com/PublicDataWorks/complaint-manager/assets/165818433/8282b8ff-31e0-4304-9139-3952e2c6c3aa)

**Comment by rnair-tw** [comment]
@rowsnr the image above has the right part cut off (as it's shifted to the right), could you repost the image where it's more centered?

**Comment by rowsnr** [comment]
![hcsoc-letterhead](https://github.com/PublicDataWorks/complaint-manager/assets/165818433/44c011ae-b1ed-4b85-a602-289ca21955aa)

updated image*** png and ai file can be found [here](https://drive.google.com/drive/folders/1Hbecr2gGKheMg0nqn8Ft_AZf4gabkGc-?usp=drive_link)

**Comment by thoughtworks-vwong** [comment]
Verified letterhead is changed on letters and matches new design - https://noipm-staging.herokuapp.com/cases/1595

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/134408135/e2e5583f-867f-429d-ba48-dedad2f80cb6)

**Comment by christina-luong** [comment]
Sent email to Cara to confirm if letterhead changes are in effect. Placing card on-hold pending response.

**Comment by christina-luong** [comment]
Followed up via email. Cara is OOO until next week. Card on-hold pending response.

**Comment by christina-luong** [comment]
@espinolaJ-TW Attached a letter that was generated today. Letterhead is not showing new commissioners.

[8-25-2023_FFR2023-0008_CAN'T HELP.pdf](https://github.com/PublicDataWorks/complaint-manager/files/15475024/8-25-2023_FFR2023-0008_CAN.T.HELP.pdf)
