### ISSUE TITLE
Copy letter templates from prod into non-prod

### ISSUE THREAD

**Issue by rnair-tw** [PublicDataWorks/complaint-manager#566]
### User Story
As a developer
I want to copy all the letter templates from prod to non-prod
So that non-prod more closely resembles prod and I can test any user issues with the letter template

### Definition of Done
We need to copy 17 letter templates from prod into non prod for Hawaii. In order to do this, update the seeder to incorporate the remaining templates so they don't disappear from non-prod. It is done when we can see Hawaii's prod letter templates in non-prod.

[Letter templates](https://drive.google.com/drive/folders/1dLTg8HBSvmXdlXO11nicPjI1JxMEP6W_)

### Acceptance Criteria
**Given** I am in local, CI and Staging
**Given** in Hawaii mode
**When** I look at the letter templates
**Then** I should see all the letter templates that Hawaii has in prod

Implementation Steps: 

- [X] Get templates from PROD (copy into sql file local complaint manager)
- [X] Create Seeder file and run sql script 
- [X] Run local app to test
- [X] Check local database and local website 
- [x] make sure CI env is working as intended 
- [ ] Pass QA testing in staging

**Comment by thoughtworks-vwong** [comment]
Verified letter templates were generated successfully in Hawaii staging.

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/0cc03277-1aa1-484b-931e-b6c436e741c2
