### ISSUE TITLE
Separate pipelines for organizations in CI and staging

### ISSUE THREAD

**Issue by rnair-tw** [PublicDataWorks/complaint-manager#569]
### User Story
As a developer
I want to create separate lower environments for New Orleans and Hawaii in CI/staging
So that I can easily test the environments, without having to manually switch between them
N.B. Splitting the non-release pipeline is not required, we can do whatever works best in that regard

### Definition of Done
- 2 more applications are created in Heroku
- There are 2 separate URLs for Hawaii and New Orleans
- For each url, it points to the corresponding organization (as seen by fields, values, functionality etc)
- This does not affect production 

### Acceptance Criteria
**Given** I am in the Hawaii url for CI/staging
**Or** I am in New Orleans url for CI/staging
**When** I test out the functionality
**Then** it should reflect the correct functionality in the environment

### Notes:
New Orleans urls will remain the same: `noipm-ci.herokuapp.com` and `noipm-staging.herokuapp.com`
New Hawaii urls will be: `hcsoc-ci.herokuapp.com` and `hcsoc-staging.herokuapp.com`

**Comment by rnair-tw** [comment]
Need to send this to Andrew for this thoughts in case there are some reasons this is not feasible

**Comment by rnair-tw** [comment]
To have a session on this (1hr session) to plan steps for this work

**Comment by rnair-tw** [comment]
Get Vivian to pair w/ a dev (tbc) on this

**Comment by andrew-rist-tw** [comment]
@sbhamani @rnair-tw have we checked with Jean Bloom about this, since it would double our Heroku bill?

**Comment by sbhamani** [comment]
> @sbhamani @rnair-tw have we checked with Jean Bloom about this, since it would double our Heroku bill?

Yup we should be fine with the cost!

**Comment by andrew-rist-tw** [comment]
Hawaii CI URL - https://hcsoc-ci-b16ff838b089.herokuapp.com/

**Comment by thoughtworks-vwong** [comment]
Hawaii components are displayed in the NOIPM site. E.g. Create new case dialogue, Facility field in incident details page.

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/0068ccf3-30ba-4af0-8831-45181be0b83b

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/134408135/b3e8c6c6-bef2-4e88-b5bc-f2869b3b2d89)

**Comment by thoughtworks-vwong** [comment]
Will close card after regression testing is complete

**Comment by thoughtworks-vwong** [comment]
Regression testing complete
