### ISSUE TITLE
People's Table Architecture Research/Planning

### ISSUE THREAD

**Issue by jeanwatts** [PublicDataWorks/complaint-manager#576]
### Business Context
People management and the structure of our future Peoples table is still an unknown that we need to flesh out.   Through Officers Table restructuring we gained a lot of context as to problems with People table implementation that would be good to keep in mind for CM2.

### Timebox
Have a checkpoint on 4/24

### Definition of Done
1. Produced documentation outlining structure of new Peoples Table
2. Outline contains instructions of how People's table can be updated and maintained by client
3. Outline accounts for how People would be attached to cases

### Notes
xxxx

**Comment by jeanwatts** [comment]
Mural Link with Structure: https://app.mural.co/t/twma7655/m/twma7655/1713464597813/ef478064693b402977a04e80b523979cc19b0655?sender=u1553b29e4e10306d55a32390

I ended up recommending a similar structure to before with some new constraints and the addition of flex fields.  I also created generic fields that could have built in functionality but the user could store what they want inside and name it as they please to give them some freedom.  All fields are designed with the idea that they don't have to be there and could be null except for the primary database id.  The Person_Type table would be a functional place to allow orgs to store multiple different types of people in the app but have them function differently.  

The stickies have some more details about how data could be implemented and used and on the right the more polished diagram just lists all the fields and data types in a more clear manner

**Comment by faraakhatTW** [comment]
> Mural Link with Structure: https://app.mural.co/t/twma7655/m/twma7655/1713464597813/ef478064693b402977a04e80b523979cc19b0655?sender=u1553b29e4e10306d55a32390
> 
> I ended up recommending a similar structure to before with some new constraints and the addition of flex fields. I also created generic fields that could have built in functionality but the user could store what they want inside and name it as they please to give them some freedom. All fields are designed with the idea that they don't have to be there and could be null except for the primary database id. The Person_Type table would be a functional place to allow orgs to store multiple different types of people in the app but have them function differently.
> 
> The stickies have some more details about how data could be implemented and used and on the right the more polished diagram just lists all the fields and data types in a more clear manner
