### ISSUE TITLE
Investigate how difficult it would be to upgrade to React 17 or 18

### ISSUE THREAD

**Issue by claireholt-tw** [PublicDataWorks/complaint-manager#594]
### Business Context
Our current React version is 16.1, which is several years behind the most recent version. This makes us hard to use newer features like the MUI X Data Grid. We want to look into seeing how difficult it would be to upgrade our React version.

### Definition of Done
We're able to give a rough estimate of how complex upgrading would be. We'll also know which packages have breaking changes that will require updating.

### Timebox
1 Day

### Acceptance Criteria
Do research/play around and answer:
- [x] Is there possible tech solution library? Name and link to documentation
  - [Unofficial adapter for React 17 for Enzyme](https://www.npmjs.com/package/@wojtekmaj/enzyme-adapter-react-17?activeTab=readme)
- [x] What are the advantages and disadvantages? 
  - refer to the ADR linked below
- [x] Is the value add worth it? 
  - refer to the ADR linked below
- [x] How difficult is implementation? 
  - refer to the ADR linked below
- [x] Record your findings in form of documentation(markdown or ADR)
  - https://github.com/Impactworkers/iw-complaint-manager/blob/main/docs/architecture-decision-records/007-upgrade-to-react-17.md 
- [x] Present/deskcheck your findings.
- [x] If approved write down the steps in a new Story Card
  - #607 

### Notes: 
N/A

**Comment by claireholt-tw** [comment]
Option 1: Upgrade from React 16 to React 18 (the latest version)
- We'd need to upgrade MUI from v4 to v5 (another major change)

**Comment by rd-huerta** [comment]
Server test results:
![Screenshot 2024-04-29 at 3 28 11 PM](https://github.com/PublicDataWorks/complaint-manager/assets/114006491/7e751afc-b033-4ce0-8e7a-4fbb9ac41286)

**Comment by rd-huerta** [comment]
### Recommendations
- Upgrade to React 17
  - Fix 7 failing tests from client tests

- Long term goal: upgrade to React 18
  - add new card for test refactoring: switch from enzyme to RTL to the backlog
 > [!TIP]
> Once we get rid of enzyme tests, it will be easy for us to upgrade to React v.18
