### ISSUE TITLE
Display all both open and closed cases in Data Dashboard

### ISSUE THREAD

**Issue by christina-luong** [PublicDataWorks/complaint-manager#599]
### User Story
As a user in New Orleans
I want to be able to see both open and closed cases in the Data Dashboard
So that I can report on this data to my management and other interested parties

### Definition of Done
Open and closed cases show up in the data dashboard (vs only closed cases) 

### Acceptance Criteria
**Given** that I am on the Data Dashboard
**When** I view the various charts on the page
**Then** I should see both open and closed cases included in the totals
**And** archived cases should be excluded (this is the existing behavior)

**Comment by heliofreitastw** [comment]
There is a feature flag called `displayAllStatusInDashboard` that when enabled allows all the statuses to be displayed. We can enable this feature flag for NO and they should be able to visualize the cases with all the statuses instead of only `Forwarded to agency` and `Closed`.

**Comment by heliofreitastw** [comment]
These checkboxes were added to allow the user to choose which case status they want to include in the visualization of the dashboard. The code is in [this branch](https://github.com/PublicDataWorks/complaint-manager/compare/feat/filter-by-case-status). The example of how it looks it is below:

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/146017664/76185ce9-b95a-43d2-8998-4c6da1d2f24e)

**Comment by rnair-tw** [comment]
![Image](https://github.com/PublicDataWorks/complaint-manager/assets/91492037/6b05907b-4497-420e-80ff-126c0d99b733)

**Comment by heliofreitastw** [comment]
In the deskcheck today @rnair-tw said to not display the checkboxes and to keep the feature flag. I will be reverting the changes, then pushing them to the master branch.

**Comment by heliofreitastw** [comment]
This is the original PR: https://github.com/PublicDataWorks/complaint-manager/pull/610

This is the original branch: https://github.com/PublicDataWorks/complaint-manager/commits/feat/filter-by-case-status/

**Comment by heliofreitastw** [comment]
@thoughtworks-vwong The code has been removed in [this commit](https://github.com/PublicDataWorks/complaint-manager/commit/7ad83a4c97beda17f620d9c3c305ace4c0edbaf1). So, there is no development to test. 

The following has been done to the client so they could see all the statuses in the data dashboard:
- I went to their production database and enabled the feature flag called `displayAllStatusInDashboard`. For this to take effect, they need to logoff and login again. Then they will be able to visualize the DataDashboard with all the statuses available.

**Comment by thoughtworks-vwong** [comment]
Verified both open and closed cases are displayed in Data Dashboard. There was a bug found where if intake source is empty, it'll display as null on the dashboard - https://github.com/PublicDataWorks/complaint-manager/issues/621

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/134408135/22d981eb-b784-4f4e-852d-f0307116e91a)
![Image](https://github.com/PublicDataWorks/complaint-manager/assets/134408135/69025d3c-8a63-407f-ba2f-ac40f1bd6c91)

**Comment by rnair-tw** [comment]
to check w/ @heliofreitastw if this needs to be pushed to prod

**Comment by heliofreitastw** [comment]
@rnair-tw @christina-luong this can be pushed to prod. It only affects NOIPM. All the code written for it does is updating a feature flag value to true.
