### ISSUE TITLE
Onboard Andrew (Dev)

### ISSUE THREAD

**Issue by rnair-tw** [PublicDataWorks/complaint-manager#612]
### Member attends relevant onboarding sessions
- [x] Account Overview (PdM, TL, XD)
   - Intro to team, roles, stakeholders and WoW
   - Intro and demo of the product
- [x] Overview of technical architecture, tech stack and technical deep dive (TL)

###  Role based checklist
All
- [x] Go through onboarding checklist on Trello (https://trello.com/b/KBvIPuf3/on-off-boarding-template-do-not-edit-anything-make-your-own-copy)

Dev
- [x] Pair with another dev to go through the dev specific onboarding items

###  Notes
- Add any blockers/issues to comments in this card

###  Impt Access (Invites sent)
- [x] Slack => unable to invite
- [x] Github
- [x] Team calendar 
- [x] Google group
- [x] Trello
- [x] Mural

**Comment by andrew-rist-tw** [comment]
Onboarding Trello - https://trello.com/b/pZ7MDT3n/onboarding-andrew-rist
