### ISSUE TITLE
Write-in directives for allegations are not appearing in referral letter

### ISSUE THREAD

**Issue by christina-luong** [PublicDataWorks/complaint-manager#617]
### Describe the bug
When users write in their own directive for allegations, this does not latter appear in the referral letter.

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/91492037/a4ee5d72-32fe-426e-9b60-075d3fd43fb2)

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/91492037/a43109fc-298a-4347-b269-1aacd4fdc0d7)

### Steps to reproduce
List any steps to reproduce behavior 
1. Go to Case Details
2. Click on Manage Allegations (under Accused section)
3. Add a new Allegation and write in a directive
4. Go back to Case Details
5. Review and Approve the letter
6. Nothing shows up in the Allegations section of the referral letter

### Expected behavior
The correct allegation should show up on the letter. This is an example:
![Image](https://github.com/PublicDataWorks/complaint-manager/assets/91492037/acc4e4d2-6b0a-4141-947c-a3fabb87a139)

### Checklist
- [x] Indicate bug severity on the right

**Additional context**
Reference `OfficerAllegation.js` for this story card.

**Comment by thoughtworks-vwong** [comment]
Verified write-in directives are appearing in referral letter.

https://github.com/PublicDataWorks/complaint-manager/assets/134408135/00cbff04-52da-4ea9-a3df-62521e727758
